// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum CSINodeDriverOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CSINodeDriver<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CSINodeDriver<'a> {
  type Inner = CSINodeDriver<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CSINodeDriver<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_NODEID: flatbuffers::VOffsetT = 6;
  pub const VT_TOPOLOGYKEYS: flatbuffers::VOffsetT = 8;
  pub const VT_ALLOCATABLE: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CSINodeDriver { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CSINodeDriverArgs<'args>
  ) -> flatbuffers::WIPOffset<CSINodeDriver<'bldr>> {
    let mut builder = CSINodeDriverBuilder::new(_fbb);
    if let Some(x) = args.allocatable { builder.add_allocatable(x); }
    if let Some(x) = args.topologyKeys { builder.add_topologyKeys(x); }
    if let Some(x) = args.nodeID { builder.add_nodeID(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CSINodeDriver::VT_NAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn nodeID(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CSINodeDriver::VT_NODEID, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn topologyKeys(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(CSINodeDriver::VT_TOPOLOGYKEYS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn allocatable(&self) -> VolumeNodeResources<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<VolumeNodeResources>>(CSINodeDriver::VT_ALLOCATABLE, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for CSINodeDriver<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("nodeID", Self::VT_NODEID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("topologyKeys", Self::VT_TOPOLOGYKEYS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<VolumeNodeResources>>("allocatable", Self::VT_ALLOCATABLE, false)?
     .finish();
    Ok(())
  }
}
pub struct CSINodeDriverArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub nodeID: Option<flatbuffers::WIPOffset<&'a str>>,
    pub topologyKeys: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub allocatable: Option<flatbuffers::WIPOffset<VolumeNodeResources<'a>>>,
}
impl<'a> Default for CSINodeDriverArgs<'a> {
  #[inline]
  fn default() -> Self {
    CSINodeDriverArgs {
      name: None,
      nodeID: None,
      topologyKeys: None,
      allocatable: None,
    }
  }
}

impl Serialize for CSINodeDriver<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("CSINodeDriver", 4)?;
      s.serialize_field("name", &self.name())?;
      s.serialize_field("nodeID", &self.nodeID())?;
      s.serialize_field("topologyKeys", &self.topologyKeys())?;
      s.serialize_field("allocatable", &self.allocatable())?;
    s.end()
  }
}

pub struct CSINodeDriverBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CSINodeDriverBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CSINodeDriver::VT_NAME, name);
  }
  #[inline]
  pub fn add_nodeID(&mut self, nodeID: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CSINodeDriver::VT_NODEID, nodeID);
  }
  #[inline]
  pub fn add_topologyKeys(&mut self, topologyKeys: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CSINodeDriver::VT_TOPOLOGYKEYS, topologyKeys);
  }
  #[inline]
  pub fn add_allocatable(&mut self, allocatable: flatbuffers::WIPOffset<VolumeNodeResources<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<VolumeNodeResources>>(CSINodeDriver::VT_ALLOCATABLE, allocatable);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CSINodeDriverBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CSINodeDriverBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CSINodeDriver<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CSINodeDriver<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CSINodeDriver");
      ds.field("name", &self.name());
      ds.field("nodeID", &self.nodeID());
      ds.field("topologyKeys", &self.topologyKeys());
      ds.field("allocatable", &self.allocatable());
      ds.finish()
  }
}
