// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum CSIStorageCapacityOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CSIStorageCapacity<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CSIStorageCapacity<'a> {
  type Inner = CSIStorageCapacity<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CSIStorageCapacity<'a> {
  pub const VT_METADATA: flatbuffers::VOffsetT = 4;
  pub const VT_NODETOPOLOGY: flatbuffers::VOffsetT = 6;
  pub const VT_STORAGECLASSNAME: flatbuffers::VOffsetT = 8;
  pub const VT_CAPACITY: flatbuffers::VOffsetT = 10;
  pub const VT_MAXIMUMVOLUMESIZE: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CSIStorageCapacity { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CSIStorageCapacityArgs<'args>
  ) -> flatbuffers::WIPOffset<CSIStorageCapacity<'bldr>> {
    let mut builder = CSIStorageCapacityBuilder::new(_fbb);
    if let Some(x) = args.maximumVolumeSize { builder.add_maximumVolumeSize(x); }
    if let Some(x) = args.capacity { builder.add_capacity(x); }
    if let Some(x) = args.storageClassName { builder.add_storageClassName(x); }
    if let Some(x) = args.nodeTopology { builder.add_nodeTopology(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    builder.finish()
  }


  #[inline]
  pub fn metadata(&self) -> super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>(CSIStorageCapacity::VT_METADATA, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn nodeTopology(&self) -> super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(CSIStorageCapacity::VT_NODETOPOLOGY, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn storageClassName(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CSIStorageCapacity::VT_STORAGECLASSNAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn capacity(&self) -> super::super::super::apimachinery::pkg::api::resource::Quantity<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>(CSIStorageCapacity::VT_CAPACITY, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn maximumVolumeSize(&self) -> super::super::super::apimachinery::pkg::api::resource::Quantity<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>(CSIStorageCapacity::VT_MAXIMUMVOLUMESIZE, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for CSIStorageCapacity<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>("nodeTopology", Self::VT_NODETOPOLOGY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("storageClassName", Self::VT_STORAGECLASSNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>("capacity", Self::VT_CAPACITY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>("maximumVolumeSize", Self::VT_MAXIMUMVOLUMESIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct CSIStorageCapacityArgs<'a> {
    pub metadata: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'a>>>,
    pub nodeTopology: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a>>>,
    pub storageClassName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub capacity: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity<'a>>>,
    pub maximumVolumeSize: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity<'a>>>,
}
impl<'a> Default for CSIStorageCapacityArgs<'a> {
  #[inline]
  fn default() -> Self {
    CSIStorageCapacityArgs {
      metadata: None,
      nodeTopology: None,
      storageClassName: None,
      capacity: None,
      maximumVolumeSize: None,
    }
  }
}

impl Serialize for CSIStorageCapacity<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("CSIStorageCapacity", 5)?;
      s.serialize_field("metadata", &self.metadata())?;
      s.serialize_field("nodeTopology", &self.nodeTopology())?;
      s.serialize_field("storageClassName", &self.storageClassName())?;
      s.serialize_field("capacity", &self.capacity())?;
      s.serialize_field("maximumVolumeSize", &self.maximumVolumeSize())?;
    s.end()
  }
}

pub struct CSIStorageCapacityBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CSIStorageCapacityBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_metadata(&mut self, metadata: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>(CSIStorageCapacity::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_nodeTopology(&mut self, nodeTopology: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(CSIStorageCapacity::VT_NODETOPOLOGY, nodeTopology);
  }
  #[inline]
  pub fn add_storageClassName(&mut self, storageClassName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CSIStorageCapacity::VT_STORAGECLASSNAME, storageClassName);
  }
  #[inline]
  pub fn add_capacity(&mut self, capacity: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>(CSIStorageCapacity::VT_CAPACITY, capacity);
  }
  #[inline]
  pub fn add_maximumVolumeSize(&mut self, maximumVolumeSize: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>(CSIStorageCapacity::VT_MAXIMUMVOLUMESIZE, maximumVolumeSize);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CSIStorageCapacityBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CSIStorageCapacityBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CSIStorageCapacity<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CSIStorageCapacity<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CSIStorageCapacity");
      ds.field("metadata", &self.metadata());
      ds.field("nodeTopology", &self.nodeTopology());
      ds.field("storageClassName", &self.storageClassName());
      ds.field("capacity", &self.capacity());
      ds.field("maximumVolumeSize", &self.maximumVolumeSize());
      ds.finish()
  }
}
