// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PodsMetricSourceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PodsMetricSource<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PodsMetricSource<'a> {
  type Inner = PodsMetricSource<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PodsMetricSource<'a> {
  pub const VT_METRIC: flatbuffers::VOffsetT = 4;
  pub const VT_TARGET: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PodsMetricSource { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PodsMetricSourceArgs<'args>
  ) -> flatbuffers::WIPOffset<PodsMetricSource<'bldr>> {
    let mut builder = PodsMetricSourceBuilder::new(_fbb);
    if let Some(x) = args.target { builder.add_target(x); }
    if let Some(x) = args.metric { builder.add_metric(x); }
    builder.finish()
  }


  #[inline]
  pub fn metric(&self) -> MetricIdentifier<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<MetricIdentifier>>(PodsMetricSource::VT_METRIC, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn target(&self) -> MetricTarget<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<MetricTarget>>(PodsMetricSource::VT_TARGET, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for PodsMetricSource<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<MetricIdentifier>>("metric", Self::VT_METRIC, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<MetricTarget>>("target", Self::VT_TARGET, false)?
     .finish();
    Ok(())
  }
}
pub struct PodsMetricSourceArgs<'a> {
    pub metric: Option<flatbuffers::WIPOffset<MetricIdentifier<'a>>>,
    pub target: Option<flatbuffers::WIPOffset<MetricTarget<'a>>>,
}
impl<'a> Default for PodsMetricSourceArgs<'a> {
  #[inline]
  fn default() -> Self {
    PodsMetricSourceArgs {
      metric: None,
      target: None,
    }
  }
}

impl Serialize for PodsMetricSource<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("PodsMetricSource", 2)?;
      s.serialize_field("metric", &self.metric())?;
      s.serialize_field("target", &self.target())?;
    s.end()
  }
}

pub struct PodsMetricSourceBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PodsMetricSourceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_metric(&mut self, metric: flatbuffers::WIPOffset<MetricIdentifier<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<MetricIdentifier>>(PodsMetricSource::VT_METRIC, metric);
  }
  #[inline]
  pub fn add_target(&mut self, target: flatbuffers::WIPOffset<MetricTarget<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<MetricTarget>>(PodsMetricSource::VT_TARGET, target);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PodsMetricSourceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PodsMetricSourceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PodsMetricSource<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PodsMetricSource<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PodsMetricSource");
      ds.field("metric", &self.metric());
      ds.field("target", &self.target());
      ds.finish()
  }
}
