// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum SchedulingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Scheduling<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Scheduling<'a> {
  type Inner = Scheduling<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Scheduling<'a> {
  pub const VT_NODESELECTOR: flatbuffers::VOffsetT = 4;
  pub const VT_TOLERATIONS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Scheduling { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SchedulingArgs<'args>
  ) -> flatbuffers::WIPOffset<Scheduling<'bldr>> {
    let mut builder = SchedulingBuilder::new(_fbb);
    if let Some(x) = args.tolerations { builder.add_tolerations(x); }
    if let Some(x) = args.nodeSelector { builder.add_nodeSelector(x); }
    builder.finish()
  }


  #[inline]
  pub fn nodeSelector(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<scheduling_::NodeSelectorEntry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<scheduling_::NodeSelectorEntry>>>>(Scheduling::VT_NODESELECTOR, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn tolerations(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::super::core::v_1::Toleration<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::super::core::v_1::Toleration>>>>(Scheduling::VT_TOLERATIONS, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for Scheduling<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<scheduling_::NodeSelectorEntry>>>>("nodeSelector", Self::VT_NODESELECTOR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<super::super::core::v_1::Toleration>>>>("tolerations", Self::VT_TOLERATIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct SchedulingArgs<'a> {
    pub nodeSelector: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<scheduling_::NodeSelectorEntry<'a>>>>>,
    pub tolerations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::super::core::v_1::Toleration<'a>>>>>,
}
impl<'a> Default for SchedulingArgs<'a> {
  #[inline]
  fn default() -> Self {
    SchedulingArgs {
      nodeSelector: None,
      tolerations: None,
    }
  }
}

impl Serialize for Scheduling<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("Scheduling", 2)?;
      s.serialize_field("nodeSelector", &self.nodeSelector())?;
      s.serialize_field("tolerations", &self.tolerations())?;
    s.end()
  }
}

pub struct SchedulingBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SchedulingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_nodeSelector(&mut self, nodeSelector: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<scheduling_::NodeSelectorEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Scheduling::VT_NODESELECTOR, nodeSelector);
  }
  #[inline]
  pub fn add_tolerations(&mut self, tolerations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<super::super::core::v_1::Toleration<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Scheduling::VT_TOLERATIONS, tolerations);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SchedulingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SchedulingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Scheduling<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Scheduling<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Scheduling");
      ds.field("nodeSelector", &self.nodeSelector());
      ds.field("tolerations", &self.tolerations());
      ds.finish()
  }
}
