// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ImageReviewSpecOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ImageReviewSpec<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ImageReviewSpec<'a> {
  type Inner = ImageReviewSpec<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ImageReviewSpec<'a> {
  pub const VT_CONTAINERS: flatbuffers::VOffsetT = 4;
  pub const VT_ANNOTATIONS: flatbuffers::VOffsetT = 6;
  pub const VT_NAMESPACE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ImageReviewSpec { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ImageReviewSpecArgs<'args>
  ) -> flatbuffers::WIPOffset<ImageReviewSpec<'bldr>> {
    let mut builder = ImageReviewSpecBuilder::new(_fbb);
    if let Some(x) = args.namespace { builder.add_namespace(x); }
    if let Some(x) = args.annotations { builder.add_annotations(x); }
    if let Some(x) = args.containers { builder.add_containers(x); }
    builder.finish()
  }


  #[inline]
  pub fn containers(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ImageReviewContainerSpec<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ImageReviewContainerSpec>>>>(ImageReviewSpec::VT_CONTAINERS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn annotations(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<image_review_spec_::AnnotationsEntry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<image_review_spec_::AnnotationsEntry>>>>(ImageReviewSpec::VT_ANNOTATIONS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn namespace(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ImageReviewSpec::VT_NAMESPACE, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for ImageReviewSpec<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ImageReviewContainerSpec>>>>("containers", Self::VT_CONTAINERS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<image_review_spec_::AnnotationsEntry>>>>("annotations", Self::VT_ANNOTATIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("namespace", Self::VT_NAMESPACE, false)?
     .finish();
    Ok(())
  }
}
pub struct ImageReviewSpecArgs<'a> {
    pub containers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ImageReviewContainerSpec<'a>>>>>,
    pub annotations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<image_review_spec_::AnnotationsEntry<'a>>>>>,
    pub namespace: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ImageReviewSpecArgs<'a> {
  #[inline]
  fn default() -> Self {
    ImageReviewSpecArgs {
      containers: None,
      annotations: None,
      namespace: None,
    }
  }
}

impl Serialize for ImageReviewSpec<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("ImageReviewSpec", 3)?;
      s.serialize_field("containers", &self.containers())?;
      s.serialize_field("annotations", &self.annotations())?;
      s.serialize_field("namespace", &self.namespace())?;
    s.end()
  }
}

pub struct ImageReviewSpecBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ImageReviewSpecBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_containers(&mut self, containers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ImageReviewContainerSpec<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ImageReviewSpec::VT_CONTAINERS, containers);
  }
  #[inline]
  pub fn add_annotations(&mut self, annotations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<image_review_spec_::AnnotationsEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ImageReviewSpec::VT_ANNOTATIONS, annotations);
  }
  #[inline]
  pub fn add_namespace(&mut self, namespace: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ImageReviewSpec::VT_NAMESPACE, namespace);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ImageReviewSpecBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ImageReviewSpecBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ImageReviewSpec<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ImageReviewSpec<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ImageReviewSpec");
      ds.field("containers", &self.containers());
      ds.field("annotations", &self.annotations());
      ds.field("namespace", &self.namespace());
      ds.finish()
  }
}
