// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RuleWithOperationsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RuleWithOperations<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RuleWithOperations<'a> {
  type Inner = RuleWithOperations<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RuleWithOperations<'a> {
  pub const VT_OPERATIONS: flatbuffers::VOffsetT = 4;
  pub const VT_RULE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RuleWithOperations { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RuleWithOperationsArgs<'args>
  ) -> flatbuffers::WIPOffset<RuleWithOperations<'bldr>> {
    let mut builder = RuleWithOperationsBuilder::new(_fbb);
    if let Some(x) = args.rule { builder.add_rule(x); }
    if let Some(x) = args.operations { builder.add_operations(x); }
    builder.finish()
  }


  #[inline]
  pub fn operations(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(RuleWithOperations::VT_OPERATIONS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn rule(&self) -> Rule<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Rule>>(RuleWithOperations::VT_RULE, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for RuleWithOperations<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("operations", Self::VT_OPERATIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Rule>>("rule", Self::VT_RULE, false)?
     .finish();
    Ok(())
  }
}
pub struct RuleWithOperationsArgs<'a> {
    pub operations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub rule: Option<flatbuffers::WIPOffset<Rule<'a>>>,
}
impl<'a> Default for RuleWithOperationsArgs<'a> {
  #[inline]
  fn default() -> Self {
    RuleWithOperationsArgs {
      operations: None,
      rule: None,
    }
  }
}

impl Serialize for RuleWithOperations<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("RuleWithOperations", 2)?;
      s.serialize_field("operations", &self.operations())?;
      s.serialize_field("rule", &self.rule())?;
    s.end()
  }
}

pub struct RuleWithOperationsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RuleWithOperationsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_operations(&mut self, operations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RuleWithOperations::VT_OPERATIONS, operations);
  }
  #[inline]
  pub fn add_rule(&mut self, rule: flatbuffers::WIPOffset<Rule<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Rule>>(RuleWithOperations::VT_RULE, rule);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RuleWithOperationsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RuleWithOperationsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RuleWithOperations<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RuleWithOperations<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RuleWithOperations");
      ds.field("operations", &self.operations());
      ds.field("rule", &self.rule());
      ds.finish()
  }
}
