// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ValidatingWebhookConfigurationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ValidatingWebhookConfiguration<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ValidatingWebhookConfiguration<'a> {
  type Inner = ValidatingWebhookConfiguration<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ValidatingWebhookConfiguration<'a> {
  pub const VT_METADATA: flatbuffers::VOffsetT = 4;
  pub const VT_WEBHOOKS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ValidatingWebhookConfiguration { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ValidatingWebhookConfigurationArgs<'args>
  ) -> flatbuffers::WIPOffset<ValidatingWebhookConfiguration<'bldr>> {
    let mut builder = ValidatingWebhookConfigurationBuilder::new(_fbb);
    if let Some(x) = args.Webhooks { builder.add_Webhooks(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    builder.finish()
  }


  #[inline]
  pub fn metadata(&self) -> super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>(ValidatingWebhookConfiguration::VT_METADATA, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn Webhooks(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ValidatingWebhook<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ValidatingWebhook>>>>(ValidatingWebhookConfiguration::VT_WEBHOOKS, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for ValidatingWebhookConfiguration<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ValidatingWebhook>>>>("Webhooks", Self::VT_WEBHOOKS, false)?
     .finish();
    Ok(())
  }
}
pub struct ValidatingWebhookConfigurationArgs<'a> {
    pub metadata: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'a>>>,
    pub Webhooks: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ValidatingWebhook<'a>>>>>,
}
impl<'a> Default for ValidatingWebhookConfigurationArgs<'a> {
  #[inline]
  fn default() -> Self {
    ValidatingWebhookConfigurationArgs {
      metadata: None,
      Webhooks: None,
    }
  }
}

impl Serialize for ValidatingWebhookConfiguration<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("ValidatingWebhookConfiguration", 2)?;
      s.serialize_field("metadata", &self.metadata())?;
      s.serialize_field("Webhooks", &self.Webhooks())?;
    s.end()
  }
}

pub struct ValidatingWebhookConfigurationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ValidatingWebhookConfigurationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_metadata(&mut self, metadata: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>(ValidatingWebhookConfiguration::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_Webhooks(&mut self, Webhooks: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ValidatingWebhook<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ValidatingWebhookConfiguration::VT_WEBHOOKS, Webhooks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ValidatingWebhookConfigurationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ValidatingWebhookConfigurationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ValidatingWebhookConfiguration<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ValidatingWebhookConfiguration<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ValidatingWebhookConfiguration");
      ds.field("metadata", &self.metadata());
      ds.field("Webhooks", &self.Webhooks());
      ds.finish()
  }
}
