[package]
name = "kubesman"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["cluster-types"]

[dependencies]
cluster-types = {path = "./cluster-types"}

actix-web = { version = "4.9.0" }
actix-files = { version = "0.6.6" }
env_logger = { version = "0.11.3" }
log = { version = "0.4.22" }
kube = { version = "0.93.1" }
k8s-openapi = { version = "0.22.0", features = ["latest"] }
actix-protobuf = { version = "0.11.0" }