endpoint="http://192.168.49.2:31235"
client_id="f2bef8159070776cf0bd"
client_secret="d05a43b3154aa6360e6b15f00d497dd4f1dbc410"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIE5zCCAs+gAwIBAgIDAeJAMA0GCSqGSIb3DQEBDAUAMC0xEzARBgNVBAoTCkt1
YmVybmV0ZXMxFjAUBgNVBAMMDWNlcnRzX2NsdXN0ZXIwHhcNMjQxMjIxMTk0MjM0
WhcNNDQxMjIxMTk0MjM0WjAtMRMwEQYDVQQKEwpLdWJlcm5ldGVzMRYwFAYDVQQD
DA1jZXJ0c19jbHVzdGVyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
tTlMqeyCyrhxvgc1erOsN9UWfVS48LDC8IkloxrDOVHU6TYtJa7Hl/hOB2etnP6f
eplSl64EKMtax7Q5ZCoiJt17gNyoKgDECQmwwCN+zu2ybe+5+MCl4om7w+5ynAIG
yY6Vhs8OwQzJV8hV3RD3GvQlF2BL5C3wLnAfF+2GUYR1mGt8gcTWGE1aEfJc4ee2
VSeOQ5UQxvekCqJHmCjgOG0lK3pFG5ccAPXMbzOakCnu+fIL3ys5sLsc0WWzFeBi
o5xAsCHCDsBEIXtKLRZq0ulIcTH+zjPzTs2wPf1m39BhlpLqAlCZGWRcbZwAFQAb
mFfHEyH5pMvaWPCxnghLCsmqGgBUekyiTFEN3cqf+Im2ES+tPxlmzVcYVl+DxVnP
2OeGJhstL9Wl48hch3tILizUqD1k1wMdfc0ZN90OqWKSWyKn0vN19iX9dBOcKSLg
qJNN3WKttKUGh0jryZRSBsPz2BD+QB10MPITORk58OD8/CGgbAj0+gFk7axP5Y6m
idKhKGit4d9PpFtDMi/acf56iZemFwgTjkk7DoFhikYY5LGHIXAqwX9h7rLx+mDX
c2aG7pax9zYNB7JCJk4c5LgXT2EI5aCWH2MvVyKS6w0t8DnI/GmkLp0Qled3LUwt
Iy1k0hStviBmKQDtotk4jw0q9qXuC6Y85S3kz0HKHu8CAwEAAaMQMA4wDAYDVR0T
AQH/BAIwADANBgkqhkiG9w0BAQwFAAOCAgEAcuznoUTPkOkYp28yYdDw0I0TmTXF
W/FI+6MiKND3pRNOpw8fHLAhGXHUaqO11TRalc6nnHMCo4LT8AO8batUTI9ScQTt
4Ms8Rs9tGORPW2mAlx6OhFFJtRFvrCfONCf8azAs53dOlYYDZfEp/PoTMZE2nuoK
/V7j2AS9otFVjjSWN+Va07F99jsfTzAR6dAOt1paOoKAG47F5MCbDmkvLKpUUXBc
Pw4oiogktHfjwcAwcJ/RCrxs+wNqxwHkAN3js1/OM/JALxH+LRjebG19AI3292vf
+vxlQ5LfO1lAjNhESyZZ9OSiMC6icBA48lNKBXkorcanpiN3F94Uc6CIks/wiupB
aA4p6NsPRC9ZBxMlNxsMUCAOwUMsstH1mRX5nW9R4hcmeJRHeLrkS2XeVCzoSuG2
zEv6tzt/cdewgf00Qs4O7W9eMu+g8EHxGMBbHXFB4VZhuNnnn2RnHGvcprQ3V51+
Osdf+ZEEIcvNCngluLzdr5D9oEwpOmjwTGkEFnsMJyC8iF94ygCtGhw5NTTygcoO
PQhsBU47CrSDyNKoASU7wAkEuYH96ea7gaSzrGDdoKMQ9P3K0vMAcmQHgLQTuO8b
ZPUdcEoqhRRZxE/IwS/v93WiYRI+NWdm2DGF/u6EP+oXGDXKC6Ykn93DWGKrIoUc
oRuxvvsQ5ugnY0Y=
-----END CERTIFICATE-----"""