endpoint="http://localhost:8000"
client_id="26b04dcc0f7446c3f2c2"
client_secret="43aa002632ab65ef4ddd8a7f1d9eb390b767612d"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIE4zCCAsugAwIBAgIDAeJAMA0GCSqGSIb3DQEBDQUAMCsxEzARBgNVBAoTCkt1
YmVybmV0ZXMxFDASBgNVBAMMC2NlcnRfNGVvdmQ4MB4XDTI1MDIyNjE5NDk0N1oX
DTQ1MDIyNjE5NDk0N1owKzETMBEGA1UEChMKS3ViZXJuZXRlczEUMBIGA1UEAwwL
Y2VydF80ZW92ZDgwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDOBX12
XoOsRZeDl5vnOa45PC78Zu8H6TxpPFyM+ssqWtAl2JFlakKuUWuIy6hVzlMOmWk+
XNgovJMqNGSZAYrYxVPRXeckhe1IGYbKJEyp20tMyBMcfoFYqrJDFSaey1JUEHGt
zP0gIxUXkzB+OICkEenilfGMK/+rnVkG1201YqgwTAC+HOs3EtR2qhXB00o0sApa
FXrtTr5B2W0N1nj7/fp909a3VY1Slj9s+iJ7NhTw+Iiu5sJ5+QZWC7a1Ih4ZXbZl
o+ua2FFtz98nb2ARxPyE563pPoBX9SL0XEM9lGNaGfi8s/nWDS0//+zSnqji74OF
r/t70GaTD+YJ+gQMTqqFzib89ZpzB9WBJiq2ehS9lgASlbioEGOFbkrdA1CrhwKO
UiuBYSl1tb6PIRh9bwC+CIsvKTkcL1Ap83LzO9ywOdCRHVER4/XM8UJppmuxh6Cf
jbGWzEoiKRld5ayUJAlFk0GAPhO/CKcVDrcVZ5iPcxu91F+if0UY9esaw5gxBpKC
w5OIvoZ8Sf2C2uBhU32eUa/HyXOywk/HbOyb9BtOuKPeZrjcmYvMkeP1qiMDt8KG
4C903exH+W2LhwiT+MjrlMtpVkQ8739xNxF0/aV7H/v3Rfm3iDr9O7fxFOB6aLyp
CGL6MW9VsZwXQnutyehzwak7eR20ZZSOWxyLbwIDAQABoxAwDjAMBgNVHRMBAf8E
AjAAMA0GCSqGSIb3DQEBDQUAA4ICAQAx4bmYQaOBm98K6YPlYs9enXBo4WopifZN
laFJmbLG1HN7A9/ToSfEZflrWvIbLtk6EJKWU6oKznZ2qYgbtYzjEZlb5XGaTGPo
8ibBO0jRWJeATBYERYD8pr2/qxxTAg7nh2woJvau1hfAHwTOK9XlRFqoUPGboWK7
/BgHavwG5yT+CNCelGbuRBIov1i6jcOzbyIvfJ2ppKPNFfqUaJ7TTV2OCIEC4ASD
oWGd/VBBESgj8F39lgHQxKNPuexjXrXveu98FVkq6RAEeXel1OKeZAEnNqoQoBx+
YK8tX2XCTw8Qsk4Y/XXfqy1CxHGwzCsEAEA7rarV4iv67UA03HuRGrONpHR/O04W
saEDDBcySvPhWNr50C0Mijz8cyF341OlZQgxeNlYvKfsjqE0Bx9ww1tpFgTJYNSl
bV13heIQPBAu5gtCctSnjgQlTghfyUeqxKoXHPHuxqsH5oN19Af7xmjw7eeM0wPj
5iZK9f52SVvwbEEnPCSKufNh87hDeuBTInirhPUENY6BokWxJjwuds6yS+tiu20z
SysCzVEgWzzZ5Rvu2xV65/rszAgouGO6deje0EhJcNMnMX0YSyOnEOz74XRc7pEv
brxnm1RRWSBe4XbWVvTwxgLgDwbHtmMGaTqxjAJ9iSHOJBNN2g45stYkxdzVV+QJ
u+mQkoVEGg==
-----END CERTIFICATE-----"""