endpoint="http://localhost:8000"
client_id="e953686f04e7055b698b"
client_secret="ca1044147dd343beb3288a77effd39792c760056"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIC2TCCAcGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBDQUAMCYxDjAMBgNVBAoTBWFk
bWluMRQwEgYDVQQDDAtjZXJ0XzUzNmd4OTAeFw0yNDEyMjIxNzQzMzBaFw00NDEy
MjIxNzQzMzBaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0XzUzNmd4
OTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL+Zvl/hKtjvdot7weaI
AqbvMEU4y75rER+jKo/9D0gzIHViOKrAqcYTu9wPby3ERnvj6Euem5PWyVxKbAeS
UpLHhAc9hhD8pk2lJD3zdS1xZlLbEoiu5jf+4+7aNHrkaLcgpleGL2EumwVerMVE
8Ppvi/CI/4mY4xjMORnvbFGMrUFv+UYXzauvZkCLAeoPCn7moyOzPtzVcoI6sFhe
8WsKhC+czWQmZv3XkHCynUKnwaAOkrmxp0/yOm/zTkOqIhWP4rexjs+rdtJhRt3t
zARYJJQDM2i2Ct5DEMb7IoCv8GDn4meY1xDLu+FBg7+09GfmFopYi5KMq1UCDD/7
agcCAwEAAaMQMA4wDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQ0FAAOCAQEAZkcs
islf93x+uff4dXIPq/bZ01Hg9pzVDxiK5pCN5Q7CePHvu84rrWQ0oCdAykAtnlJJ
5RrMR+fqjLZsnN6LnUObBK1e3NDqV5a3bkRMxb3zIsOXjjIha45qgp19QHcseC45
T3+ZYskmikPgiIfbtnP2XqEN3QUp3gcB0vp2xa3kw/DG09ySlinXhuFos3An2avG
d3BJs9w2jpXww1cIxugGbmNV9MSUSUUuei1nWeEFichKu+r+vug/SnIeR7j4AEzP
nU7sGznWJUpgcJoSzlQcmbUdUSorjKX/6xu3q/EYLIcVbp7L7b3VriJZjGjTuzs7
PBn2LI95jSCTLmes3A==
-----END CERTIFICATE-----"""