endpoint="http://localhost:8000"
client_id="becb1a6259881cfcae5c"
client_secret="79dcd6bf400b630cab728d83fd6b4bdd9f82aa4b"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIE4zCCAsugAwIBAgIDAeJAMA0GCSqGSIb3DQEBDQUAMCsxEzARBgNVBAoTCkt1
YmVybmV0ZXMxFDASBgNVBAMMC2NlcnRfbHplbjdmMB4XDTI0MTIyNzIxMTgzMVoX
DTQ0MTIyNzIxMTgzMVowKzETMBEGA1UEChMKS3ViZXJuZXRlczEUMBIGA1UEAwwL
Y2VydF9semVuN2YwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDdFtl3
8WEE5bd5N663hT6wpPL7SDOF6Du55ggsWnJV2I2lpkNY7UFeXyGSgR1FlYOY5lpH
0XiJwJ42YYxlvoCZpAzL/FdZhY4+mTvdV/K5p344UPITPsZEL8blxIhqDn+vBUOJ
LnyooSts55QVA3slK3zRgj9LkgQNMBw8ae0TyxQYQ3VYEIqmN3Q1XmPYriMgEe5b
gZfjPY2dGQKqNpKqvpaxvy9wWBNVVYnPBSwVyIGPx/512qhYzKz/Fb9K1CaFCr3m
1B2AyERzN0QJJQAgipuLuo4oj2lYQsZta8I3kL6LhNFoaQKlTW4keJ1wRQF2eftX
E382M5jDbT1tX5qfR69OuBQ4vhJlRq89L5RvaoM8HL8yKXY7tprJvIUjd6eRXNZi
AiuU5awb7elUAkbkNBG3QbY908o2RT+tv8LGviVjAHKgPpNspgN3rO7GbpkQc6mz
yVS6wFRHyD0YJ3h6EbzJwhed7D054v5FDwE28Bn/yIT5NkgMRYvBs5GdhjTX3lg0
dnKv5Qxlu3VWXy99QLtgYaDYDXku8FTRZq9SMDI4kITAFnWprZSSzPnJQs50yynD
SBOaTXmnoLpUgGO5p11a9jW2ooZ0yRLieIMiXB7rk70XhYQYTHT9ikRD6FKi7/4Q
wlkisk4Ywny0ukOMKD9BaE+g9P5eF6FG7T+J8QIDAQABoxAwDjAMBgNVHRMBAf8E
AjAAMA0GCSqGSIb3DQEBDQUAA4ICAQCjC1cPjfS29oghEOGojw/v2roLIQXGg0b1
I+kDTTYcqAkN1TUiaLwKBBCytvPjt68jm1O9B/x3K14FL1cLT9aWJGPzICNbR2B0
0cb2WlPCWKiv6ztcaJ7mhZopd4sJhgToypKEHIN95a2OctLjKMWlW2Lv6LL1gVCa
iIITIYpg1BjeMfI/gXqRlGlvALswl2RupB2x3gXVIyXbHoATMn0Ek1FbzwZk32+p
4IBkFbMAebsEB1ZjKPsGQuvX7x8ISHRZs5UFJL/4IgPPjXPslwEBPsgFqZZoU+5C
cF55d1M/LORjRlkr64fAZjE7StfSVah1IvjtkAib6Z+2ChzAHHU+/yz1d4VEE4XP
YpYq54/1gfxen8sXGr6IsiOSSKat4nYwxlxuZDQpGGxqpjJHtq1hRjlry0pERvCy
zRPOhw/0O+TClHQ3VcUYNg8D2dfSHvcwkCh4bonP5EIU9S6Lpn4N3nf06LvMMfyl
3st2kA/bZBYR8Zwekwvq1XpBN2oDwtIJKPbSCy93jhRBfUaK+THwr1YPTmflZoBG
5Wz/vAb0vRp4Eo/4pbpddj46+LBpISCgEcx/w75+lEXkpEhR5bfAoGPbpByLFSP/
mrFFvaLSrvwrDmQGdOuuC+2vL00+LfgeSSi3G8Km90XwwbkkiattHKaoIieHBoWy
XDGw/itUVw==
-----END CERTIFICATE-----"""
domain="http://localhost:9000"