endpoint="http://localhost:8000"
client_id="c044b7f8c71d04f26e52"
client_secret="c032d64f441c3361ab4821f0769eca9700028b4e"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIE4zCCAsugAwIBAgIDAeJAMA0GCSqGSIb3DQEBDQUAMCsxEzARBgNVBAoTCkt1
YmVybmV0ZXMxFDASBgNVBAMMC2NlcnRfMGtrdjI0MB4XDTI1MDMwMTEyMzgyMloX
DTQ1MDMwMTEyMzgyMlowKzETMBEGA1UEChMKS3ViZXJuZXRlczEUMBIGA1UEAwwL
Y2VydF8wa2t2MjQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCZUn2T
N1WMP9DMXKn+cPNgb+eKhBzzDdTlm/T5atVKhHMxfTg5gdO080HHwt86x1OqNA29
6af882enMvEkzA4B6/asw9rhub1B6sP/+tzHa47pfRwcp/8LwhTLx0iPVXkO6tcv
TTTUT/SctokMLq4UxtiX0vzBQADz1Clf6N0Uph2rau69SW9ajx4R+w6LLeW2YG5b
BdaR2xhIGKktuoDsBy3ykAHo0Av8xjHIF++Sjt54FuHPQN/Tmj7Pk5PRLsKnIOvL
me4R3e+sL5wjP69YjE8IkycDK6Gss2bLiVKekvYkOTrUTKfbDggIY9V5jDvsWbDw
ddJyGCXZrUURRiHoFUO8xmq12dV8YwsD+FiX7x9gpkq3+hVxWYJrUPJqbycGI+/J
R3sHrkImTKw/fR9OSuYbMPUEJ9bAPUekEWe9rFTJB/dLxeSzZ7Bs1842y18nBIQ4
mudwMhHeV0mYo1TA+cdKIQjwW3kt9TkYbIV4c55mKyVVUH/oa29D6mYcD0fgEYMp
P5c/zF44cCBDB05ArPw7AN46bs60DFC82IMLPMzvYJwfuIr3zfGtt+l+07P9fZYX
JTzfhKzDQTvZX4SQPvjxfGxm9f6IwavU/QWDR29ocEC8qGsx29ruKt5QNpL1sewh
ig4Vkhdg7EKUGo6ymyLImPpGDyb4q9RKcet7QQIDAQABoxAwDjAMBgNVHRMBAf8E
AjAAMA0GCSqGSIb3DQEBDQUAA4ICAQBWTahVWJylPY75qOXKQN+S6LOypLVeA116
orI25GzXFLdobA7JutIy8T6uXXWpiXXLpCdMTKcar9oN6havvMO+4ohCnI1NJqkq
ueLdXdtq0NLJJ/t5kGY7YoPrIIp6TedQX+cqqoU4VYRFWsQJTVChYWzqTC5V01oU
Ji8OkaGPGMk4eFPlKrtdTPRNAVKCgcxVJAzjGW+z+OvbRt/Gj6bH3i6PqhI2ZSwk
sc7n8ZXFPUScmOwLRTJ70ZpZQPmOCj5cz5jnM0tLNaSoR+5b1KCQFhaEpWE4oFdM
IuuK5m7T7b/S24QfkvESFPiIadZeoBEmFl0SLlDq6H/J1tuu8IP+4M5NZRbDlVCY
TlLEjRqILfrieFuQ9igzrPhE5d34zjafKA1Kbg8G3JxWkHaE+uPJJaf7cWl+ez5r
X2mHVNltGQg85gkcfq51qO+/4gSxLDl3sZ4aaJx4lE3DvWsCgVrrMXC0OTebeTGF
xXoTySmorNPkgEKrVJ1ipMJ70hgg7JuEClUseETyPJQIujb9USBLog61pho3vGOQ
CZhDADuidyuMzI+Cwu2Ci0l38qq/pEJa/ArPAB3BzCMEABKMFB9AUZTL1hycv14c
MU4sma2g/tIqZVKcAJNB/1EM9l7jRWPDxIkE4xE8JYRO0kU+Zc6SFAOoDqZcOLtZ
HA48qp23bw==
-----END CERTIFICATE-----"""