endpoint="http://localhost:8000"
client_id="1c1e0a611af6f09cb383"
client_secret="f93e6595ceb0530185cf509b0a4b0ae699018c0c"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIE4zCCAsugAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCsxEzARBgNVBAoTCkt1
YmVybmV0ZXMxFDASBgNVBAMMC2NlcnRfanFkNWZqMB4XDTI1MDExMTAxMDg1MloX
DTQ1MDExMTAxMDg1MlowKzETMBEGA1UEChMKS3ViZXJuZXRlczEUMBIGA1UEAwwL
Y2VydF9qcWQ1ZmowggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDkAwtJ
sDwnkv3pyrZYAY2cHv1YAIi7RSZ+2qSD0VU2TJtRFxg5mD9JpcqmgVu9u8UKPHyt
0kJygfD2OTMjxPYfEncAI7kh7/fKnbIcFMd5ACxThAPkhvPsf5BkJRDIjCpI+2C7
3Iy/5Ju+GGlmCbqByZ0/UKEfqCxJjjcxWslqZNEcvKVsHOTDXcetbjIjMPq54w9v
QCZAWvo/Jv4cdGMtuI5EMn+fPXVF+bv4oQ1rDv/DdYCuJhxhqeSAZCi4rs6u088M
KY4ECWHIzarNizoDxdlbvRNslQWfppLJwYT5c3myEtXRD4TLhkZICOZ1m73S8xS7
nqMZ6WJqvjMtM+U8zT5JLXhYkPPgOpZwNC1w3LG0qu6J7X5d/seWWCDCdesjJJXI
FAlGye6nhDqnOqwO2PUDvoXnKb7qbiTV3mdBsT17vkTQ63ONHRI1FDfIcYG1Ya8C
bpSxTb+JY4/i837oH8ezmuR9vmb4xFktmy9qnzz0mJBAK0kYNZESa7ykyfDY+yvI
Py5/LOfRVLSLgll+MlqYmD/PpyxO5IiFxuPcGm9Pa8HeNYBZ9H8SZ8WtqIsKUFjR
XNm6nGD2j50HwAKGc63AKU5Po9n3zCTtxt949nyYRKOTdIahoyO6DJp2+0yzx6sS
veJhRchWzdlk12OqaO3apDIlJ18FW71NM8M5BQIDAQABoxAwDjAMBgNVHRMBAf8E
AjAAMA0GCSqGSIb3DQEBCwUAA4ICAQAmn9vJYmeb31Bp5PF7bLqoeHDiha/ryQ3r
HzrLo4F57s/VHKeYgZI+gyPvDeKhwB27OxjQsiAkw2KYQEXScuZJY+eAo+JcNTuK
DOJ+nYLb6Cn5JwcS9FOymVDJe9mu5fSUzegGsVt/5OTX6qm6vksd41K3TmD/Vs29
bhdIHSGqVtaqou7A/u87wByiXdYH5CgUJ/bM4IJs/y8DUy/fqEQKT92SLi+9lCOz
/+kTGJ/unJx7mVsM+mkfq52Mhso0o7Og1wXaNsEQGgTtkX03XZ4PMPw9R16w3ksQ
Emu5+bcm1FnpoaDT8q/RwEhWFRrgzaZ3SvgyW5LNwgOS9KVs18h6yD2JTaOee5vU
jtvRMkDXhma9l6O/PqtfF5KDwFpigGYK4dridyLaRO1S9f67z0j8mzv0dlwZHNKU
bKKbdDJ5Wm0XkVlKrIljawuN63GKO5EwMtILsVuK9tKtEaaLuq5qFAadzp3ZAurP
4UZ+Gw5eYa6GEBlD+vtqwGp1S8GrYoIrq8ktiYo1/f+gOrtfGafMsT0aWM2wzZJc
3KK5syPmL/A46z+WQhBkJ9nP6NkZSMZj4KLbNrzAFQui5maa5dfp0YemYVacDtaO
NRjny05CNEuXZvd2X7jBbX2URLd4UC2leSWm8nxaeAsVcZzFEUgPKdllLS7KGQsc
F4RXn6nKBA==
-----END CERTIFICATE-----"""