endpoint="http://localhost:30218"
client_id="af4145fa9c3e94b65eea"
client_secret="a892161c0edf0a743142d9e2353c979eb40460ae"
org_name="Kubernetes"
app_name="Cluster"
certificate="""-----BEGIN CERTIFICATE-----
MIIE3zCCAsegAwIBAgIDAeJAMA0GCSqGSIb3DQEBDQUAMCkxEzARBgNVBAoTCkt1
YmVybmV0ZXMxEjAQBgNVBAMMCWNlcnRzX25ldzAeFw0yNDEyMjEyMTAwMzZaFw00
NDEyMjEyMTAwMzZaMCkxEzARBgNVBAoTCkt1YmVybmV0ZXMxEjAQBgNVBAMMCWNl
cnRzX25ldzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKvAHui7GZ+y
5g3iNpwoUxGWBnGPFngikndMioDTnAUNcZeLkpjCTPiiQve2dJ6vNJ0z32Y2kq+o
mcWpL9Wxg+IDnij0vDu9gtLy7d3rbP/n5ZE+L3yEffI9MqunG7DKJ7EkuL73OcU/
w94e6TKaDJvanLrHrsYGM1sZvcLkVLY91o0Z/+xCxGO4wrr2Dpv90nnqLePhfiba
3DRB+FyQ7n03JkhKxFJSu0/CU1W1wDOb3nTnrksDRjNQroaxpyiexogrUVuv0jF/
6ikxbbMSOs2DrWNue247HrjPw+FvWEwRZIZIeLnspz5Qu1saMeLvHq/Ae1YFY5eD
+CQFX9OatzgVcdohXXDX7Atvj4imRnL4FlytIrVkX2sP8dhMkGbVXfvM6JE7GALU
sh8gu/nt0c2U3a2fn4HijHIxIrSZYmJqmkwRz+DuOt3JzLch3qWnAsYzx4P3c3fS
JYdzY7BJ4jnR8/Wpyg//3B+O+1JV+MYqtPj6Ju/uRYeBmFghip8C+VodarVFzgfd
3DKp8zwMXtixWF+PbNFnIzpfQbS4UKBaVoKuI2Y2CVgF+TyNhHcp87E7u22KbFEo
8Yp3EeuQ60EP65mI1L0L/LcqolM3Jx8aeN6PdP2HqY9cdgyPsIrhMjl17u4iHZAe
xSrp4H9F6pp6f5FYUUmuSTYA2FCxjOstAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAw
DQYJKoZIhvcNAQENBQADggIBAHrbuMtdXt3yMk5cHnJIJWKWufQsSi5fc97OA+n8
oy6+hj/3ZARV4AonoAoVxm6C+3UPv//p/alhwOjlPcM4uKi08Py7HS70j96w6I5U
xxbF+2IfqQV/e8vx4572Tw/MgZ4mBHla20YvUbipke3xxzdKS2crjTy1iagT8Nwd
Pe++2Xy+UYVK0ZfIq5CpL9DJvjSAFXct+4IDYeuD7+4Nt2vYqSEI+rBcJ+JBteuX
K1PIUMCsUOHQl1yH3Et8iu/otDpizGPOrWZT1t6TJ/5ptONjdF4+Ijule8Ozpt50
S6WAW544k9KpHJxexFALNvvnATiimpxJ6LADGOhpqcs2JYqbPN+YCBRKqGoaRFiy
GgxsCecFgAwNWHKmktLhgf1KRMAtMbGmizOuuszB3q+ipaR5JBxafYgh1oJ61P4U
eXGfFhOkPZ7UxR+bw4j8RDyOOF3jqBcFopmJFlwkNHoKSJr9cELnvqqVWBLHXGrZ
yTDM3uSmhQS/fwVgO3HNHBJOS0Jv5fCRCZsS/2cvLKViyF/V6saI5F081xGn/wmV
r/gJ8XZ9y/GvT4gt5cBkQV0wAb35Dr/VUdMJjetbbPKHhnwcsqQi5vZXpCFXwInE
hG/G0lRg+tq5ClJ73kx42+aNcrCkkPqUwYZAq7b5afPB7sxO21y+oUwBL4/CxEu4
Q2hs
-----END CERTIFICATE-----"""