// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum MetricValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MetricValue<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MetricValue<'a> {
  type Inner = MetricValue<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> MetricValue<'a> {
  pub const VT_DESCRIBEDOBJECT: flatbuffers::VOffsetT = 4;
  pub const VT_METRICNAME: flatbuffers::VOffsetT = 6;
  pub const VT_TIMESTAMP: flatbuffers::VOffsetT = 8;
  pub const VT_WINDOW: flatbuffers::VOffsetT = 10;
  pub const VT_VALUE: flatbuffers::VOffsetT = 12;
  pub const VT_SELECTOR: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MetricValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MetricValueArgs<'args>
  ) -> flatbuffers::WIPOffset<MetricValue<'bldr>> {
    let mut builder = MetricValueBuilder::new(_fbb);
    builder.add_window(args.window);
    if let Some(x) = args.selector { builder.add_selector(x); }
    if let Some(x) = args.value { builder.add_value(x); }
    if let Some(x) = args.timestamp { builder.add_timestamp(x); }
    if let Some(x) = args.metricName { builder.add_metricName(x); }
    if let Some(x) = args.describedObject { builder.add_describedObject(x); }
    builder.finish()
  }


  #[inline]
  pub fn describedObject(&self) -> super::super::super::super::super::api::core::v_1::ObjectReference<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::super::super::api::core::v_1::ObjectReference>>(MetricValue::VT_DESCRIBEDOBJECT, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn metricName(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MetricValue::VT_METRICNAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn timestamp(&self) -> super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::Time<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::Time>>(MetricValue::VT_TIMESTAMP, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn window(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(MetricValue::VT_WINDOW, Some(0)).unwrap()}
  }
  #[inline]
  pub fn value(&self) -> super::super::super::super::super::apimachinery::pkg::api::resource::Quantity<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::super::super::apimachinery::pkg::api::resource::Quantity>>(MetricValue::VT_VALUE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn selector(&self) -> super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(MetricValue::VT_SELECTOR, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for MetricValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::super::super::api::core::v_1::ObjectReference>>("describedObject", Self::VT_DESCRIBEDOBJECT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("metricName", Self::VT_METRICNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::Time>>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<i64>("window", Self::VT_WINDOW, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::super::super::apimachinery::pkg::api::resource::Quantity>>("value", Self::VT_VALUE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>("selector", Self::VT_SELECTOR, false)?
     .finish();
    Ok(())
  }
}
pub struct MetricValueArgs<'a> {
    pub describedObject: Option<flatbuffers::WIPOffset<super::super::super::super::super::api::core::v_1::ObjectReference<'a>>>,
    pub metricName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub timestamp: Option<flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::Time<'a>>>,
    pub window: i64,
    pub value: Option<flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::api::resource::Quantity<'a>>>,
    pub selector: Option<flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a>>>,
}
impl<'a> Default for MetricValueArgs<'a> {
  #[inline]
  fn default() -> Self {
    MetricValueArgs {
      describedObject: None,
      metricName: None,
      timestamp: None,
      window: 0,
      value: None,
      selector: None,
    }
  }
}

impl Serialize for MetricValue<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("MetricValue", 6)?;
      s.serialize_field("describedObject", &self.describedObject())?;
      s.serialize_field("metricName", &self.metricName())?;
      s.serialize_field("timestamp", &self.timestamp())?;
      s.serialize_field("window", &self.window())?;
      s.serialize_field("value", &self.value())?;
      s.serialize_field("selector", &self.selector())?;
    s.end()
  }
}

pub struct MetricValueBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MetricValueBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_describedObject(&mut self, describedObject: flatbuffers::WIPOffset<super::super::super::super::super::api::core::v_1::ObjectReference<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::super::super::api::core::v_1::ObjectReference>>(MetricValue::VT_DESCRIBEDOBJECT, describedObject);
  }
  #[inline]
  pub fn add_metricName(&mut self, metricName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MetricValue::VT_METRICNAME, metricName);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::Time<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::Time>>(MetricValue::VT_TIMESTAMP, timestamp);
  }
  #[inline]
  pub fn add_window(&mut self, window: i64) {
    self.fbb_.push_slot::<i64>(MetricValue::VT_WINDOW, window, 0);
  }
  #[inline]
  pub fn add_value(&mut self, value: flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::api::resource::Quantity<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::api::resource::Quantity>>(MetricValue::VT_VALUE, value);
  }
  #[inline]
  pub fn add_selector(&mut self, selector: flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(MetricValue::VT_SELECTOR, selector);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MetricValueBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MetricValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MetricValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MetricValue<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MetricValue");
      ds.field("describedObject", &self.describedObject());
      ds.field("metricName", &self.metricName());
      ds.field("timestamp", &self.timestamp());
      ds.field("window", &self.window());
      ds.field("value", &self.value());
      ds.field("selector", &self.selector());
      ds.finish()
  }
}
