// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum MetricSpecOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MetricSpec<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MetricSpec<'a> {
  type Inner = MetricSpec<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> MetricSpec<'a> {
  pub const VT_TYPE_: flatbuffers::VOffsetT = 4;
  pub const VT_OBJECT: flatbuffers::VOffsetT = 6;
  pub const VT_PODS: flatbuffers::VOffsetT = 8;
  pub const VT_RESOURCE: flatbuffers::VOffsetT = 10;
  pub const VT_CONTAINERRESOURCE: flatbuffers::VOffsetT = 12;
  pub const VT_EXTERNAL: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MetricSpec { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MetricSpecArgs<'args>
  ) -> flatbuffers::WIPOffset<MetricSpec<'bldr>> {
    let mut builder = MetricSpecBuilder::new(_fbb);
    if let Some(x) = args.external { builder.add_external(x); }
    if let Some(x) = args.containerResource { builder.add_containerResource(x); }
    if let Some(x) = args.resource { builder.add_resource(x); }
    if let Some(x) = args.pods { builder.add_pods(x); }
    if let Some(x) = args.object { builder.add_object(x); }
    if let Some(x) = args.type_ { builder.add_type_(x); }
    builder.finish()
  }


  #[inline]
  pub fn type_(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MetricSpec::VT_TYPE_, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn object(&self) -> ObjectMetricSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ObjectMetricSource>>(MetricSpec::VT_OBJECT, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn pods(&self) -> PodsMetricSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<PodsMetricSource>>(MetricSpec::VT_PODS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn resource(&self) -> ResourceMetricSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ResourceMetricSource>>(MetricSpec::VT_RESOURCE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn containerResource(&self) -> ContainerResourceMetricSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ContainerResourceMetricSource>>(MetricSpec::VT_CONTAINERRESOURCE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn external(&self) -> ExternalMetricSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ExternalMetricSource>>(MetricSpec::VT_EXTERNAL, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for MetricSpec<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("type_", Self::VT_TYPE_, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<ObjectMetricSource>>("object", Self::VT_OBJECT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<PodsMetricSource>>("pods", Self::VT_PODS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<ResourceMetricSource>>("resource", Self::VT_RESOURCE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<ContainerResourceMetricSource>>("containerResource", Self::VT_CONTAINERRESOURCE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<ExternalMetricSource>>("external", Self::VT_EXTERNAL, false)?
     .finish();
    Ok(())
  }
}
pub struct MetricSpecArgs<'a> {
    pub type_: Option<flatbuffers::WIPOffset<&'a str>>,
    pub object: Option<flatbuffers::WIPOffset<ObjectMetricSource<'a>>>,
    pub pods: Option<flatbuffers::WIPOffset<PodsMetricSource<'a>>>,
    pub resource: Option<flatbuffers::WIPOffset<ResourceMetricSource<'a>>>,
    pub containerResource: Option<flatbuffers::WIPOffset<ContainerResourceMetricSource<'a>>>,
    pub external: Option<flatbuffers::WIPOffset<ExternalMetricSource<'a>>>,
}
impl<'a> Default for MetricSpecArgs<'a> {
  #[inline]
  fn default() -> Self {
    MetricSpecArgs {
      type_: None,
      object: None,
      pods: None,
      resource: None,
      containerResource: None,
      external: None,
    }
  }
}

impl Serialize for MetricSpec<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("MetricSpec", 6)?;
      s.serialize_field("type_", &self.type_())?;
      s.serialize_field("object", &self.object())?;
      s.serialize_field("pods", &self.pods())?;
      s.serialize_field("resource", &self.resource())?;
      s.serialize_field("containerResource", &self.containerResource())?;
      s.serialize_field("external", &self.external())?;
    s.end()
  }
}

pub struct MetricSpecBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MetricSpecBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_type_(&mut self, type_: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MetricSpec::VT_TYPE_, type_);
  }
  #[inline]
  pub fn add_object(&mut self, object: flatbuffers::WIPOffset<ObjectMetricSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<ObjectMetricSource>>(MetricSpec::VT_OBJECT, object);
  }
  #[inline]
  pub fn add_pods(&mut self, pods: flatbuffers::WIPOffset<PodsMetricSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<PodsMetricSource>>(MetricSpec::VT_PODS, pods);
  }
  #[inline]
  pub fn add_resource(&mut self, resource: flatbuffers::WIPOffset<ResourceMetricSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<ResourceMetricSource>>(MetricSpec::VT_RESOURCE, resource);
  }
  #[inline]
  pub fn add_containerResource(&mut self, containerResource: flatbuffers::WIPOffset<ContainerResourceMetricSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<ContainerResourceMetricSource>>(MetricSpec::VT_CONTAINERRESOURCE, containerResource);
  }
  #[inline]
  pub fn add_external(&mut self, external: flatbuffers::WIPOffset<ExternalMetricSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<ExternalMetricSource>>(MetricSpec::VT_EXTERNAL, external);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MetricSpecBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MetricSpecBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MetricSpec<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MetricSpec<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MetricSpec");
      ds.field("type_", &self.type_());
      ds.field("object", &self.object());
      ds.field("pods", &self.pods());
      ds.field("resource", &self.resource());
      ds.field("containerResource", &self.containerResource());
      ds.field("external", &self.external());
      ds.finish()
  }
}
