// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PodsMetricStatusOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PodsMetricStatus<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PodsMetricStatus<'a> {
  type Inner = PodsMetricStatus<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PodsMetricStatus<'a> {
  pub const VT_METRICNAME: flatbuffers::VOffsetT = 4;
  pub const VT_CURRENTAVERAGEVALUE: flatbuffers::VOffsetT = 6;
  pub const VT_SELECTOR: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PodsMetricStatus { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PodsMetricStatusArgs<'args>
  ) -> flatbuffers::WIPOffset<PodsMetricStatus<'bldr>> {
    let mut builder = PodsMetricStatusBuilder::new(_fbb);
    if let Some(x) = args.selector { builder.add_selector(x); }
    if let Some(x) = args.currentAverageValue { builder.add_currentAverageValue(x); }
    if let Some(x) = args.metricName { builder.add_metricName(x); }
    builder.finish()
  }


  #[inline]
  pub fn metricName(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PodsMetricStatus::VT_METRICNAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn currentAverageValue(&self) -> super::super::super::apimachinery::pkg::api::resource::Quantity<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>(PodsMetricStatus::VT_CURRENTAVERAGEVALUE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn selector(&self) -> super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(PodsMetricStatus::VT_SELECTOR, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for PodsMetricStatus<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("metricName", Self::VT_METRICNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>("currentAverageValue", Self::VT_CURRENTAVERAGEVALUE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>("selector", Self::VT_SELECTOR, false)?
     .finish();
    Ok(())
  }
}
pub struct PodsMetricStatusArgs<'a> {
    pub metricName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub currentAverageValue: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity<'a>>>,
    pub selector: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a>>>,
}
impl<'a> Default for PodsMetricStatusArgs<'a> {
  #[inline]
  fn default() -> Self {
    PodsMetricStatusArgs {
      metricName: None,
      currentAverageValue: None,
      selector: None,
    }
  }
}

impl Serialize for PodsMetricStatus<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("PodsMetricStatus", 3)?;
      s.serialize_field("metricName", &self.metricName())?;
      s.serialize_field("currentAverageValue", &self.currentAverageValue())?;
      s.serialize_field("selector", &self.selector())?;
    s.end()
  }
}

pub struct PodsMetricStatusBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PodsMetricStatusBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_metricName(&mut self, metricName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PodsMetricStatus::VT_METRICNAME, metricName);
  }
  #[inline]
  pub fn add_currentAverageValue(&mut self, currentAverageValue: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::api::resource::Quantity>>(PodsMetricStatus::VT_CURRENTAVERAGEVALUE, currentAverageValue);
  }
  #[inline]
  pub fn add_selector(&mut self, selector: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(PodsMetricStatus::VT_SELECTOR, selector);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PodsMetricStatusBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PodsMetricStatusBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PodsMetricStatus<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PodsMetricStatus<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PodsMetricStatus");
      ds.field("metricName", &self.metricName());
      ds.field("currentAverageValue", &self.currentAverageValue());
      ds.field("selector", &self.selector());
      ds.finish()
  }
}
