// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RuntimeClassOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RuntimeClass<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RuntimeClass<'a> {
  type Inner = RuntimeClass<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RuntimeClass<'a> {
  pub const VT_METADATA: flatbuffers::VOffsetT = 4;
  pub const VT_HANDLER: flatbuffers::VOffsetT = 6;
  pub const VT_OVERHEAD: flatbuffers::VOffsetT = 8;
  pub const VT_SCHEDULING: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RuntimeClass { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RuntimeClassArgs<'args>
  ) -> flatbuffers::WIPOffset<RuntimeClass<'bldr>> {
    let mut builder = RuntimeClassBuilder::new(_fbb);
    if let Some(x) = args.scheduling { builder.add_scheduling(x); }
    if let Some(x) = args.overhead { builder.add_overhead(x); }
    if let Some(x) = args.handler { builder.add_handler(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    builder.finish()
  }


  #[inline]
  pub fn metadata(&self) -> super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>(RuntimeClass::VT_METADATA, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn handler(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RuntimeClass::VT_HANDLER, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn overhead(&self) -> Overhead<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Overhead>>(RuntimeClass::VT_OVERHEAD, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn scheduling(&self) -> Scheduling<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Scheduling>>(RuntimeClass::VT_SCHEDULING, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for RuntimeClass<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("handler", Self::VT_HANDLER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Overhead>>("overhead", Self::VT_OVERHEAD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Scheduling>>("scheduling", Self::VT_SCHEDULING, false)?
     .finish();
    Ok(())
  }
}
pub struct RuntimeClassArgs<'a> {
    pub metadata: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'a>>>,
    pub handler: Option<flatbuffers::WIPOffset<&'a str>>,
    pub overhead: Option<flatbuffers::WIPOffset<Overhead<'a>>>,
    pub scheduling: Option<flatbuffers::WIPOffset<Scheduling<'a>>>,
}
impl<'a> Default for RuntimeClassArgs<'a> {
  #[inline]
  fn default() -> Self {
    RuntimeClassArgs {
      metadata: None,
      handler: None,
      overhead: None,
      scheduling: None,
    }
  }
}

impl Serialize for RuntimeClass<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("RuntimeClass", 4)?;
      s.serialize_field("metadata", &self.metadata())?;
      s.serialize_field("handler", &self.handler())?;
      s.serialize_field("overhead", &self.overhead())?;
      s.serialize_field("scheduling", &self.scheduling())?;
    s.end()
  }
}

pub struct RuntimeClassBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RuntimeClassBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_metadata(&mut self, metadata: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::ObjectMeta>>(RuntimeClass::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_handler(&mut self, handler: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RuntimeClass::VT_HANDLER, handler);
  }
  #[inline]
  pub fn add_overhead(&mut self, overhead: flatbuffers::WIPOffset<Overhead<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Overhead>>(RuntimeClass::VT_OVERHEAD, overhead);
  }
  #[inline]
  pub fn add_scheduling(&mut self, scheduling: flatbuffers::WIPOffset<Scheduling<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Scheduling>>(RuntimeClass::VT_SCHEDULING, scheduling);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RuntimeClassBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RuntimeClassBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RuntimeClass<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RuntimeClass<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RuntimeClass");
      ds.field("metadata", &self.metadata());
      ds.field("handler", &self.handler());
      ds.field("overhead", &self.overhead());
      ds.field("scheduling", &self.scheduling());
      ds.finish()
  }
}
