// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PortworxVolumeSourceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PortworxVolumeSource<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PortworxVolumeSource<'a> {
  type Inner = PortworxVolumeSource<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PortworxVolumeSource<'a> {
  pub const VT_VOLUMEID: flatbuffers::VOffsetT = 4;
  pub const VT_FSTYPE: flatbuffers::VOffsetT = 6;
  pub const VT_READONLY: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PortworxVolumeSource { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PortworxVolumeSourceArgs<'args>
  ) -> flatbuffers::WIPOffset<PortworxVolumeSource<'bldr>> {
    let mut builder = PortworxVolumeSourceBuilder::new(_fbb);
    if let Some(x) = args.fsType { builder.add_fsType(x); }
    if let Some(x) = args.volumeID { builder.add_volumeID(x); }
    builder.add_readOnly(args.readOnly);
    builder.finish()
  }


  #[inline]
  pub fn volumeID(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PortworxVolumeSource::VT_VOLUMEID, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn fsType(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PortworxVolumeSource::VT_FSTYPE, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn readOnly(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PortworxVolumeSource::VT_READONLY, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for PortworxVolumeSource<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("volumeID", Self::VT_VOLUMEID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("fsType", Self::VT_FSTYPE, false)?
     .visit_field::<bool>("readOnly", Self::VT_READONLY, false)?
     .finish();
    Ok(())
  }
}
pub struct PortworxVolumeSourceArgs<'a> {
    pub volumeID: Option<flatbuffers::WIPOffset<&'a str>>,
    pub fsType: Option<flatbuffers::WIPOffset<&'a str>>,
    pub readOnly: bool,
}
impl<'a> Default for PortworxVolumeSourceArgs<'a> {
  #[inline]
  fn default() -> Self {
    PortworxVolumeSourceArgs {
      volumeID: None,
      fsType: None,
      readOnly: false,
    }
  }
}

impl Serialize for PortworxVolumeSource<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("PortworxVolumeSource", 3)?;
      s.serialize_field("volumeID", &self.volumeID())?;
      s.serialize_field("fsType", &self.fsType())?;
      s.serialize_field("readOnly", &self.readOnly())?;
    s.end()
  }
}

pub struct PortworxVolumeSourceBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PortworxVolumeSourceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_volumeID(&mut self, volumeID: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PortworxVolumeSource::VT_VOLUMEID, volumeID);
  }
  #[inline]
  pub fn add_fsType(&mut self, fsType: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PortworxVolumeSource::VT_FSTYPE, fsType);
  }
  #[inline]
  pub fn add_readOnly(&mut self, readOnly: bool) {
    self.fbb_.push_slot::<bool>(PortworxVolumeSource::VT_READONLY, readOnly, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PortworxVolumeSourceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PortworxVolumeSourceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PortworxVolumeSource<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PortworxVolumeSource<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PortworxVolumeSource");
      ds.field("volumeID", &self.volumeID());
      ds.field("fsType", &self.fsType());
      ds.field("readOnly", &self.readOnly());
      ds.finish()
  }
}
