// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PersistentVolumeSourceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PersistentVolumeSource<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PersistentVolumeSource<'a> {
  type Inner = PersistentVolumeSource<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PersistentVolumeSource<'a> {
  pub const VT_GCEPERSISTENTDISK: flatbuffers::VOffsetT = 4;
  pub const VT_AWSELASTICBLOCKSTORE: flatbuffers::VOffsetT = 6;
  pub const VT_HOSTPATH: flatbuffers::VOffsetT = 8;
  pub const VT_GLUSTERFS: flatbuffers::VOffsetT = 10;
  pub const VT_NFS: flatbuffers::VOffsetT = 12;
  pub const VT_RBD: flatbuffers::VOffsetT = 14;
  pub const VT_ISCSI: flatbuffers::VOffsetT = 16;
  pub const VT_CINDER: flatbuffers::VOffsetT = 18;
  pub const VT_CEPHFS: flatbuffers::VOffsetT = 20;
  pub const VT_FC: flatbuffers::VOffsetT = 22;
  pub const VT_FLOCKER: flatbuffers::VOffsetT = 24;
  pub const VT_FLEXVOLUME: flatbuffers::VOffsetT = 26;
  pub const VT_AZUREFILE: flatbuffers::VOffsetT = 28;
  pub const VT_VSPHEREVOLUME: flatbuffers::VOffsetT = 30;
  pub const VT_QUOBYTE: flatbuffers::VOffsetT = 32;
  pub const VT_AZUREDISK: flatbuffers::VOffsetT = 34;
  pub const VT_PHOTONPERSISTENTDISK: flatbuffers::VOffsetT = 36;
  pub const VT_PORTWORXVOLUME: flatbuffers::VOffsetT = 38;
  pub const VT_SCALEIO: flatbuffers::VOffsetT = 40;
  pub const VT_LOCAL: flatbuffers::VOffsetT = 42;
  pub const VT_STORAGEOS: flatbuffers::VOffsetT = 44;
  pub const VT_CSI: flatbuffers::VOffsetT = 46;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PersistentVolumeSource { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PersistentVolumeSourceArgs<'args>
  ) -> flatbuffers::WIPOffset<PersistentVolumeSource<'bldr>> {
    let mut builder = PersistentVolumeSourceBuilder::new(_fbb);
    if let Some(x) = args.csi { builder.add_csi(x); }
    if let Some(x) = args.storageos { builder.add_storageos(x); }
    if let Some(x) = args.local { builder.add_local(x); }
    if let Some(x) = args.scaleIO { builder.add_scaleIO(x); }
    if let Some(x) = args.portworxVolume { builder.add_portworxVolume(x); }
    if let Some(x) = args.photonPersistentDisk { builder.add_photonPersistentDisk(x); }
    if let Some(x) = args.azureDisk { builder.add_azureDisk(x); }
    if let Some(x) = args.quobyte { builder.add_quobyte(x); }
    if let Some(x) = args.vsphereVolume { builder.add_vsphereVolume(x); }
    if let Some(x) = args.azureFile { builder.add_azureFile(x); }
    if let Some(x) = args.flexVolume { builder.add_flexVolume(x); }
    if let Some(x) = args.flocker { builder.add_flocker(x); }
    if let Some(x) = args.fc { builder.add_fc(x); }
    if let Some(x) = args.cephfs { builder.add_cephfs(x); }
    if let Some(x) = args.cinder { builder.add_cinder(x); }
    if let Some(x) = args.iscsi { builder.add_iscsi(x); }
    if let Some(x) = args.rbd { builder.add_rbd(x); }
    if let Some(x) = args.nfs { builder.add_nfs(x); }
    if let Some(x) = args.glusterfs { builder.add_glusterfs(x); }
    if let Some(x) = args.hostPath { builder.add_hostPath(x); }
    if let Some(x) = args.awsElasticBlockStore { builder.add_awsElasticBlockStore(x); }
    if let Some(x) = args.gcePersistentDisk { builder.add_gcePersistentDisk(x); }
    builder.finish()
  }


  #[inline]
  pub fn gcePersistentDisk(&self) -> GCEPersistentDiskVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<GCEPersistentDiskVolumeSource>>(PersistentVolumeSource::VT_GCEPERSISTENTDISK, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn awsElasticBlockStore(&self) -> AWSElasticBlockStoreVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<AWSElasticBlockStoreVolumeSource>>(PersistentVolumeSource::VT_AWSELASTICBLOCKSTORE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn hostPath(&self) -> HostPathVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<HostPathVolumeSource>>(PersistentVolumeSource::VT_HOSTPATH, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn glusterfs(&self) -> GlusterfsPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<GlusterfsPersistentVolumeSource>>(PersistentVolumeSource::VT_GLUSTERFS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn nfs(&self) -> NFSVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<NFSVolumeSource>>(PersistentVolumeSource::VT_NFS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn rbd(&self) -> RBDPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<RBDPersistentVolumeSource>>(PersistentVolumeSource::VT_RBD, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn iscsi(&self) -> ISCSIPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ISCSIPersistentVolumeSource>>(PersistentVolumeSource::VT_ISCSI, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn cinder(&self) -> CinderPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<CinderPersistentVolumeSource>>(PersistentVolumeSource::VT_CINDER, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn cephfs(&self) -> CephFSPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<CephFSPersistentVolumeSource>>(PersistentVolumeSource::VT_CEPHFS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn fc(&self) -> FCVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<FCVolumeSource>>(PersistentVolumeSource::VT_FC, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn flocker(&self) -> FlockerVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<FlockerVolumeSource>>(PersistentVolumeSource::VT_FLOCKER, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn flexVolume(&self) -> FlexPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<FlexPersistentVolumeSource>>(PersistentVolumeSource::VT_FLEXVOLUME, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn azureFile(&self) -> AzureFilePersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<AzureFilePersistentVolumeSource>>(PersistentVolumeSource::VT_AZUREFILE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn vsphereVolume(&self) -> VsphereVirtualDiskVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<VsphereVirtualDiskVolumeSource>>(PersistentVolumeSource::VT_VSPHEREVOLUME, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn quobyte(&self) -> QuobyteVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<QuobyteVolumeSource>>(PersistentVolumeSource::VT_QUOBYTE, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn azureDisk(&self) -> AzureDiskVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<AzureDiskVolumeSource>>(PersistentVolumeSource::VT_AZUREDISK, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn photonPersistentDisk(&self) -> PhotonPersistentDiskVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<PhotonPersistentDiskVolumeSource>>(PersistentVolumeSource::VT_PHOTONPERSISTENTDISK, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn portworxVolume(&self) -> PortworxVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<PortworxVolumeSource>>(PersistentVolumeSource::VT_PORTWORXVOLUME, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn scaleIO(&self) -> ScaleIOPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ScaleIOPersistentVolumeSource>>(PersistentVolumeSource::VT_SCALEIO, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn local(&self) -> LocalVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<LocalVolumeSource>>(PersistentVolumeSource::VT_LOCAL, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn storageos(&self) -> StorageOSPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<StorageOSPersistentVolumeSource>>(PersistentVolumeSource::VT_STORAGEOS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn csi(&self) -> CSIPersistentVolumeSource<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<CSIPersistentVolumeSource>>(PersistentVolumeSource::VT_CSI, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for PersistentVolumeSource<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<GCEPersistentDiskVolumeSource>>("gcePersistentDisk", Self::VT_GCEPERSISTENTDISK, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<AWSElasticBlockStoreVolumeSource>>("awsElasticBlockStore", Self::VT_AWSELASTICBLOCKSTORE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<HostPathVolumeSource>>("hostPath", Self::VT_HOSTPATH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<GlusterfsPersistentVolumeSource>>("glusterfs", Self::VT_GLUSTERFS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<NFSVolumeSource>>("nfs", Self::VT_NFS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<RBDPersistentVolumeSource>>("rbd", Self::VT_RBD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<ISCSIPersistentVolumeSource>>("iscsi", Self::VT_ISCSI, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<CinderPersistentVolumeSource>>("cinder", Self::VT_CINDER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<CephFSPersistentVolumeSource>>("cephfs", Self::VT_CEPHFS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<FCVolumeSource>>("fc", Self::VT_FC, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<FlockerVolumeSource>>("flocker", Self::VT_FLOCKER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<FlexPersistentVolumeSource>>("flexVolume", Self::VT_FLEXVOLUME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<AzureFilePersistentVolumeSource>>("azureFile", Self::VT_AZUREFILE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<VsphereVirtualDiskVolumeSource>>("vsphereVolume", Self::VT_VSPHEREVOLUME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<QuobyteVolumeSource>>("quobyte", Self::VT_QUOBYTE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<AzureDiskVolumeSource>>("azureDisk", Self::VT_AZUREDISK, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<PhotonPersistentDiskVolumeSource>>("photonPersistentDisk", Self::VT_PHOTONPERSISTENTDISK, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<PortworxVolumeSource>>("portworxVolume", Self::VT_PORTWORXVOLUME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<ScaleIOPersistentVolumeSource>>("scaleIO", Self::VT_SCALEIO, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<LocalVolumeSource>>("local", Self::VT_LOCAL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<StorageOSPersistentVolumeSource>>("storageos", Self::VT_STORAGEOS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<CSIPersistentVolumeSource>>("csi", Self::VT_CSI, false)?
     .finish();
    Ok(())
  }
}
pub struct PersistentVolumeSourceArgs<'a> {
    pub gcePersistentDisk: Option<flatbuffers::WIPOffset<GCEPersistentDiskVolumeSource<'a>>>,
    pub awsElasticBlockStore: Option<flatbuffers::WIPOffset<AWSElasticBlockStoreVolumeSource<'a>>>,
    pub hostPath: Option<flatbuffers::WIPOffset<HostPathVolumeSource<'a>>>,
    pub glusterfs: Option<flatbuffers::WIPOffset<GlusterfsPersistentVolumeSource<'a>>>,
    pub nfs: Option<flatbuffers::WIPOffset<NFSVolumeSource<'a>>>,
    pub rbd: Option<flatbuffers::WIPOffset<RBDPersistentVolumeSource<'a>>>,
    pub iscsi: Option<flatbuffers::WIPOffset<ISCSIPersistentVolumeSource<'a>>>,
    pub cinder: Option<flatbuffers::WIPOffset<CinderPersistentVolumeSource<'a>>>,
    pub cephfs: Option<flatbuffers::WIPOffset<CephFSPersistentVolumeSource<'a>>>,
    pub fc: Option<flatbuffers::WIPOffset<FCVolumeSource<'a>>>,
    pub flocker: Option<flatbuffers::WIPOffset<FlockerVolumeSource<'a>>>,
    pub flexVolume: Option<flatbuffers::WIPOffset<FlexPersistentVolumeSource<'a>>>,
    pub azureFile: Option<flatbuffers::WIPOffset<AzureFilePersistentVolumeSource<'a>>>,
    pub vsphereVolume: Option<flatbuffers::WIPOffset<VsphereVirtualDiskVolumeSource<'a>>>,
    pub quobyte: Option<flatbuffers::WIPOffset<QuobyteVolumeSource<'a>>>,
    pub azureDisk: Option<flatbuffers::WIPOffset<AzureDiskVolumeSource<'a>>>,
    pub photonPersistentDisk: Option<flatbuffers::WIPOffset<PhotonPersistentDiskVolumeSource<'a>>>,
    pub portworxVolume: Option<flatbuffers::WIPOffset<PortworxVolumeSource<'a>>>,
    pub scaleIO: Option<flatbuffers::WIPOffset<ScaleIOPersistentVolumeSource<'a>>>,
    pub local: Option<flatbuffers::WIPOffset<LocalVolumeSource<'a>>>,
    pub storageos: Option<flatbuffers::WIPOffset<StorageOSPersistentVolumeSource<'a>>>,
    pub csi: Option<flatbuffers::WIPOffset<CSIPersistentVolumeSource<'a>>>,
}
impl<'a> Default for PersistentVolumeSourceArgs<'a> {
  #[inline]
  fn default() -> Self {
    PersistentVolumeSourceArgs {
      gcePersistentDisk: None,
      awsElasticBlockStore: None,
      hostPath: None,
      glusterfs: None,
      nfs: None,
      rbd: None,
      iscsi: None,
      cinder: None,
      cephfs: None,
      fc: None,
      flocker: None,
      flexVolume: None,
      azureFile: None,
      vsphereVolume: None,
      quobyte: None,
      azureDisk: None,
      photonPersistentDisk: None,
      portworxVolume: None,
      scaleIO: None,
      local: None,
      storageos: None,
      csi: None,
    }
  }
}

impl Serialize for PersistentVolumeSource<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("PersistentVolumeSource", 22)?;
      s.serialize_field("gcePersistentDisk", &self.gcePersistentDisk())?;
      s.serialize_field("awsElasticBlockStore", &self.awsElasticBlockStore())?;
      s.serialize_field("hostPath", &self.hostPath())?;
      s.serialize_field("glusterfs", &self.glusterfs())?;
      s.serialize_field("nfs", &self.nfs())?;
      s.serialize_field("rbd", &self.rbd())?;
      s.serialize_field("iscsi", &self.iscsi())?;
      s.serialize_field("cinder", &self.cinder())?;
      s.serialize_field("cephfs", &self.cephfs())?;
      s.serialize_field("fc", &self.fc())?;
      s.serialize_field("flocker", &self.flocker())?;
      s.serialize_field("flexVolume", &self.flexVolume())?;
      s.serialize_field("azureFile", &self.azureFile())?;
      s.serialize_field("vsphereVolume", &self.vsphereVolume())?;
      s.serialize_field("quobyte", &self.quobyte())?;
      s.serialize_field("azureDisk", &self.azureDisk())?;
      s.serialize_field("photonPersistentDisk", &self.photonPersistentDisk())?;
      s.serialize_field("portworxVolume", &self.portworxVolume())?;
      s.serialize_field("scaleIO", &self.scaleIO())?;
      s.serialize_field("local", &self.local())?;
      s.serialize_field("storageos", &self.storageos())?;
      s.serialize_field("csi", &self.csi())?;
    s.end()
  }
}

pub struct PersistentVolumeSourceBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PersistentVolumeSourceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_gcePersistentDisk(&mut self, gcePersistentDisk: flatbuffers::WIPOffset<GCEPersistentDiskVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<GCEPersistentDiskVolumeSource>>(PersistentVolumeSource::VT_GCEPERSISTENTDISK, gcePersistentDisk);
  }
  #[inline]
  pub fn add_awsElasticBlockStore(&mut self, awsElasticBlockStore: flatbuffers::WIPOffset<AWSElasticBlockStoreVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<AWSElasticBlockStoreVolumeSource>>(PersistentVolumeSource::VT_AWSELASTICBLOCKSTORE, awsElasticBlockStore);
  }
  #[inline]
  pub fn add_hostPath(&mut self, hostPath: flatbuffers::WIPOffset<HostPathVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<HostPathVolumeSource>>(PersistentVolumeSource::VT_HOSTPATH, hostPath);
  }
  #[inline]
  pub fn add_glusterfs(&mut self, glusterfs: flatbuffers::WIPOffset<GlusterfsPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<GlusterfsPersistentVolumeSource>>(PersistentVolumeSource::VT_GLUSTERFS, glusterfs);
  }
  #[inline]
  pub fn add_nfs(&mut self, nfs: flatbuffers::WIPOffset<NFSVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<NFSVolumeSource>>(PersistentVolumeSource::VT_NFS, nfs);
  }
  #[inline]
  pub fn add_rbd(&mut self, rbd: flatbuffers::WIPOffset<RBDPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<RBDPersistentVolumeSource>>(PersistentVolumeSource::VT_RBD, rbd);
  }
  #[inline]
  pub fn add_iscsi(&mut self, iscsi: flatbuffers::WIPOffset<ISCSIPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<ISCSIPersistentVolumeSource>>(PersistentVolumeSource::VT_ISCSI, iscsi);
  }
  #[inline]
  pub fn add_cinder(&mut self, cinder: flatbuffers::WIPOffset<CinderPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<CinderPersistentVolumeSource>>(PersistentVolumeSource::VT_CINDER, cinder);
  }
  #[inline]
  pub fn add_cephfs(&mut self, cephfs: flatbuffers::WIPOffset<CephFSPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<CephFSPersistentVolumeSource>>(PersistentVolumeSource::VT_CEPHFS, cephfs);
  }
  #[inline]
  pub fn add_fc(&mut self, fc: flatbuffers::WIPOffset<FCVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<FCVolumeSource>>(PersistentVolumeSource::VT_FC, fc);
  }
  #[inline]
  pub fn add_flocker(&mut self, flocker: flatbuffers::WIPOffset<FlockerVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<FlockerVolumeSource>>(PersistentVolumeSource::VT_FLOCKER, flocker);
  }
  #[inline]
  pub fn add_flexVolume(&mut self, flexVolume: flatbuffers::WIPOffset<FlexPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<FlexPersistentVolumeSource>>(PersistentVolumeSource::VT_FLEXVOLUME, flexVolume);
  }
  #[inline]
  pub fn add_azureFile(&mut self, azureFile: flatbuffers::WIPOffset<AzureFilePersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<AzureFilePersistentVolumeSource>>(PersistentVolumeSource::VT_AZUREFILE, azureFile);
  }
  #[inline]
  pub fn add_vsphereVolume(&mut self, vsphereVolume: flatbuffers::WIPOffset<VsphereVirtualDiskVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<VsphereVirtualDiskVolumeSource>>(PersistentVolumeSource::VT_VSPHEREVOLUME, vsphereVolume);
  }
  #[inline]
  pub fn add_quobyte(&mut self, quobyte: flatbuffers::WIPOffset<QuobyteVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<QuobyteVolumeSource>>(PersistentVolumeSource::VT_QUOBYTE, quobyte);
  }
  #[inline]
  pub fn add_azureDisk(&mut self, azureDisk: flatbuffers::WIPOffset<AzureDiskVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<AzureDiskVolumeSource>>(PersistentVolumeSource::VT_AZUREDISK, azureDisk);
  }
  #[inline]
  pub fn add_photonPersistentDisk(&mut self, photonPersistentDisk: flatbuffers::WIPOffset<PhotonPersistentDiskVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<PhotonPersistentDiskVolumeSource>>(PersistentVolumeSource::VT_PHOTONPERSISTENTDISK, photonPersistentDisk);
  }
  #[inline]
  pub fn add_portworxVolume(&mut self, portworxVolume: flatbuffers::WIPOffset<PortworxVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<PortworxVolumeSource>>(PersistentVolumeSource::VT_PORTWORXVOLUME, portworxVolume);
  }
  #[inline]
  pub fn add_scaleIO(&mut self, scaleIO: flatbuffers::WIPOffset<ScaleIOPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<ScaleIOPersistentVolumeSource>>(PersistentVolumeSource::VT_SCALEIO, scaleIO);
  }
  #[inline]
  pub fn add_local(&mut self, local: flatbuffers::WIPOffset<LocalVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<LocalVolumeSource>>(PersistentVolumeSource::VT_LOCAL, local);
  }
  #[inline]
  pub fn add_storageos(&mut self, storageos: flatbuffers::WIPOffset<StorageOSPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<StorageOSPersistentVolumeSource>>(PersistentVolumeSource::VT_STORAGEOS, storageos);
  }
  #[inline]
  pub fn add_csi(&mut self, csi: flatbuffers::WIPOffset<CSIPersistentVolumeSource<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<CSIPersistentVolumeSource>>(PersistentVolumeSource::VT_CSI, csi);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PersistentVolumeSourceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PersistentVolumeSourceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PersistentVolumeSource<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PersistentVolumeSource<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PersistentVolumeSource");
      ds.field("gcePersistentDisk", &self.gcePersistentDisk());
      ds.field("awsElasticBlockStore", &self.awsElasticBlockStore());
      ds.field("hostPath", &self.hostPath());
      ds.field("glusterfs", &self.glusterfs());
      ds.field("nfs", &self.nfs());
      ds.field("rbd", &self.rbd());
      ds.field("iscsi", &self.iscsi());
      ds.field("cinder", &self.cinder());
      ds.field("cephfs", &self.cephfs());
      ds.field("fc", &self.fc());
      ds.field("flocker", &self.flocker());
      ds.field("flexVolume", &self.flexVolume());
      ds.field("azureFile", &self.azureFile());
      ds.field("vsphereVolume", &self.vsphereVolume());
      ds.field("quobyte", &self.quobyte());
      ds.field("azureDisk", &self.azureDisk());
      ds.field("photonPersistentDisk", &self.photonPersistentDisk());
      ds.field("portworxVolume", &self.portworxVolume());
      ds.field("scaleIO", &self.scaleIO());
      ds.field("local", &self.local());
      ds.field("storageos", &self.storageos());
      ds.field("csi", &self.csi());
      ds.finish()
  }
}
