// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum StorageVersionStatusOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StorageVersionStatus<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for StorageVersionStatus<'a> {
  type Inner = StorageVersionStatus<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> StorageVersionStatus<'a> {
  pub const VT_STORAGEVERSIONS: flatbuffers::VOffsetT = 4;
  pub const VT_COMMONENCODINGVERSION: flatbuffers::VOffsetT = 6;
  pub const VT_CONDITIONS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    StorageVersionStatus { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StorageVersionStatusArgs<'args>
  ) -> flatbuffers::WIPOffset<StorageVersionStatus<'bldr>> {
    let mut builder = StorageVersionStatusBuilder::new(_fbb);
    if let Some(x) = args.conditions { builder.add_conditions(x); }
    if let Some(x) = args.commonEncodingVersion { builder.add_commonEncodingVersion(x); }
    if let Some(x) = args.storageVersions { builder.add_storageVersions(x); }
    builder.finish()
  }


  #[inline]
  pub fn storageVersions(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ServerStorageVersion<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ServerStorageVersion>>>>(StorageVersionStatus::VT_STORAGEVERSIONS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn commonEncodingVersion(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(StorageVersionStatus::VT_COMMONENCODINGVERSION, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn conditions(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<StorageVersionCondition<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<StorageVersionCondition>>>>(StorageVersionStatus::VT_CONDITIONS, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for StorageVersionStatus<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ServerStorageVersion>>>>("storageVersions", Self::VT_STORAGEVERSIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("commonEncodingVersion", Self::VT_COMMONENCODINGVERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<StorageVersionCondition>>>>("conditions", Self::VT_CONDITIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct StorageVersionStatusArgs<'a> {
    pub storageVersions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ServerStorageVersion<'a>>>>>,
    pub commonEncodingVersion: Option<flatbuffers::WIPOffset<&'a str>>,
    pub conditions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<StorageVersionCondition<'a>>>>>,
}
impl<'a> Default for StorageVersionStatusArgs<'a> {
  #[inline]
  fn default() -> Self {
    StorageVersionStatusArgs {
      storageVersions: None,
      commonEncodingVersion: None,
      conditions: None,
    }
  }
}

impl Serialize for StorageVersionStatus<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("StorageVersionStatus", 3)?;
      s.serialize_field("storageVersions", &self.storageVersions())?;
      s.serialize_field("commonEncodingVersion", &self.commonEncodingVersion())?;
      s.serialize_field("conditions", &self.conditions())?;
    s.end()
  }
}

pub struct StorageVersionStatusBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StorageVersionStatusBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_storageVersions(&mut self, storageVersions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ServerStorageVersion<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(StorageVersionStatus::VT_STORAGEVERSIONS, storageVersions);
  }
  #[inline]
  pub fn add_commonEncodingVersion(&mut self, commonEncodingVersion: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(StorageVersionStatus::VT_COMMONENCODINGVERSION, commonEncodingVersion);
  }
  #[inline]
  pub fn add_conditions(&mut self, conditions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<StorageVersionCondition<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(StorageVersionStatus::VT_CONDITIONS, conditions);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> StorageVersionStatusBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StorageVersionStatusBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<StorageVersionStatus<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for StorageVersionStatus<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("StorageVersionStatus");
      ds.field("storageVersions", &self.storageVersions());
      ds.field("commonEncodingVersion", &self.commonEncodingVersion());
      ds.field("conditions", &self.conditions());
      ds.finish()
  }
}
