// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum NamedResourcesFilterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NamedResourcesFilter<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NamedResourcesFilter<'a> {
  type Inner = NamedResourcesFilter<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NamedResourcesFilter<'a> {
  pub const VT_SELECTOR: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NamedResourcesFilter { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NamedResourcesFilterArgs<'args>
  ) -> flatbuffers::WIPOffset<NamedResourcesFilter<'bldr>> {
    let mut builder = NamedResourcesFilterBuilder::new(_fbb);
    if let Some(x) = args.selector { builder.add_selector(x); }
    builder.finish()
  }


  #[inline]
  pub fn selector(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NamedResourcesFilter::VT_SELECTOR, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for NamedResourcesFilter<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("selector", Self::VT_SELECTOR, false)?
     .finish();
    Ok(())
  }
}
pub struct NamedResourcesFilterArgs<'a> {
    pub selector: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for NamedResourcesFilterArgs<'a> {
  #[inline]
  fn default() -> Self {
    NamedResourcesFilterArgs {
      selector: None,
    }
  }
}

impl Serialize for NamedResourcesFilter<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("NamedResourcesFilter", 1)?;
      s.serialize_field("selector", &self.selector())?;
    s.end()
  }
}

pub struct NamedResourcesFilterBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NamedResourcesFilterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_selector(&mut self, selector: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NamedResourcesFilter::VT_SELECTOR, selector);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NamedResourcesFilterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NamedResourcesFilterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NamedResourcesFilter<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NamedResourcesFilter<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NamedResourcesFilter");
      ds.field("selector", &self.selector());
      ds.finish()
  }
}
