// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum NamedResourcesResourcesOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NamedResourcesResources<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NamedResourcesResources<'a> {
  type Inner = NamedResourcesResources<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NamedResourcesResources<'a> {
  pub const VT_INSTANCES: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NamedResourcesResources { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NamedResourcesResourcesArgs<'args>
  ) -> flatbuffers::WIPOffset<NamedResourcesResources<'bldr>> {
    let mut builder = NamedResourcesResourcesBuilder::new(_fbb);
    if let Some(x) = args.instances { builder.add_instances(x); }
    builder.finish()
  }


  #[inline]
  pub fn instances(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NamedResourcesInstance<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NamedResourcesInstance>>>>(NamedResourcesResources::VT_INSTANCES, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for NamedResourcesResources<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<NamedResourcesInstance>>>>("instances", Self::VT_INSTANCES, false)?
     .finish();
    Ok(())
  }
}
pub struct NamedResourcesResourcesArgs<'a> {
    pub instances: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NamedResourcesInstance<'a>>>>>,
}
impl<'a> Default for NamedResourcesResourcesArgs<'a> {
  #[inline]
  fn default() -> Self {
    NamedResourcesResourcesArgs {
      instances: None,
    }
  }
}

impl Serialize for NamedResourcesResources<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("NamedResourcesResources", 1)?;
      s.serialize_field("instances", &self.instances())?;
    s.end()
  }
}

pub struct NamedResourcesResourcesBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NamedResourcesResourcesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_instances(&mut self, instances: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<NamedResourcesInstance<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NamedResourcesResources::VT_INSTANCES, instances);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NamedResourcesResourcesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NamedResourcesResourcesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NamedResourcesResources<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NamedResourcesResources<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NamedResourcesResources");
      ds.field("instances", &self.instances());
      ds.finish()
  }
}
