// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PatchOptionsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PatchOptions<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PatchOptions<'a> {
  type Inner = PatchOptions<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PatchOptions<'a> {
  pub const VT_DRYRUN: flatbuffers::VOffsetT = 4;
  pub const VT_FORCE: flatbuffers::VOffsetT = 6;
  pub const VT_FIELDMANAGER: flatbuffers::VOffsetT = 8;
  pub const VT_FIELDVALIDATION: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PatchOptions { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PatchOptionsArgs<'args>
  ) -> flatbuffers::WIPOffset<PatchOptions<'bldr>> {
    let mut builder = PatchOptionsBuilder::new(_fbb);
    if let Some(x) = args.fieldValidation { builder.add_fieldValidation(x); }
    if let Some(x) = args.fieldManager { builder.add_fieldManager(x); }
    if let Some(x) = args.dryRun { builder.add_dryRun(x); }
    builder.add_force(args.force);
    builder.finish()
  }


  #[inline]
  pub fn dryRun(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(PatchOptions::VT_DRYRUN, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn force(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PatchOptions::VT_FORCE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn fieldManager(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PatchOptions::VT_FIELDMANAGER, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn fieldValidation(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PatchOptions::VT_FIELDVALIDATION, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for PatchOptions<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("dryRun", Self::VT_DRYRUN, false)?
     .visit_field::<bool>("force", Self::VT_FORCE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("fieldManager", Self::VT_FIELDMANAGER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("fieldValidation", Self::VT_FIELDVALIDATION, false)?
     .finish();
    Ok(())
  }
}
pub struct PatchOptionsArgs<'a> {
    pub dryRun: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub force: bool,
    pub fieldManager: Option<flatbuffers::WIPOffset<&'a str>>,
    pub fieldValidation: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PatchOptionsArgs<'a> {
  #[inline]
  fn default() -> Self {
    PatchOptionsArgs {
      dryRun: None,
      force: false,
      fieldManager: None,
      fieldValidation: None,
    }
  }
}

impl Serialize for PatchOptions<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("PatchOptions", 4)?;
      s.serialize_field("dryRun", &self.dryRun())?;
      s.serialize_field("force", &self.force())?;
      s.serialize_field("fieldManager", &self.fieldManager())?;
      s.serialize_field("fieldValidation", &self.fieldValidation())?;
    s.end()
  }
}

pub struct PatchOptionsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PatchOptionsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_dryRun(&mut self, dryRun: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PatchOptions::VT_DRYRUN, dryRun);
  }
  #[inline]
  pub fn add_force(&mut self, force: bool) {
    self.fbb_.push_slot::<bool>(PatchOptions::VT_FORCE, force, false);
  }
  #[inline]
  pub fn add_fieldManager(&mut self, fieldManager: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PatchOptions::VT_FIELDMANAGER, fieldManager);
  }
  #[inline]
  pub fn add_fieldValidation(&mut self, fieldValidation: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PatchOptions::VT_FIELDVALIDATION, fieldValidation);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PatchOptionsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PatchOptionsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PatchOptions<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PatchOptions<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PatchOptions");
      ds.field("dryRun", &self.dryRun());
      ds.field("force", &self.force());
      ds.field("fieldManager", &self.fieldManager());
      ds.field("fieldValidation", &self.fieldValidation());
      ds.finish()
  }
}
