// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum CrossVersionObjectReferenceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CrossVersionObjectReference<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CrossVersionObjectReference<'a> {
  type Inner = CrossVersionObjectReference<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CrossVersionObjectReference<'a> {
  pub const VT_KIND: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_APIVERSION: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CrossVersionObjectReference { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CrossVersionObjectReferenceArgs<'args>
  ) -> flatbuffers::WIPOffset<CrossVersionObjectReference<'bldr>> {
    let mut builder = CrossVersionObjectReferenceBuilder::new(_fbb);
    if let Some(x) = args.apiVersion { builder.add_apiVersion(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    if let Some(x) = args.kind { builder.add_kind(x); }
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CrossVersionObjectReference::VT_KIND, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CrossVersionObjectReference::VT_NAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn apiVersion(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CrossVersionObjectReference::VT_APIVERSION, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for CrossVersionObjectReference<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("kind", Self::VT_KIND, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("apiVersion", Self::VT_APIVERSION, false)?
     .finish();
    Ok(())
  }
}
pub struct CrossVersionObjectReferenceArgs<'a> {
    pub kind: Option<flatbuffers::WIPOffset<&'a str>>,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub apiVersion: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for CrossVersionObjectReferenceArgs<'a> {
  #[inline]
  fn default() -> Self {
    CrossVersionObjectReferenceArgs {
      kind: None,
      name: None,
      apiVersion: None,
    }
  }
}

impl Serialize for CrossVersionObjectReference<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("CrossVersionObjectReference", 3)?;
      s.serialize_field("kind", &self.kind())?;
      s.serialize_field("name", &self.name())?;
      s.serialize_field("apiVersion", &self.apiVersion())?;
    s.end()
  }
}

pub struct CrossVersionObjectReferenceBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CrossVersionObjectReferenceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CrossVersionObjectReference::VT_KIND, kind);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CrossVersionObjectReference::VT_NAME, name);
  }
  #[inline]
  pub fn add_apiVersion(&mut self, apiVersion: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CrossVersionObjectReference::VT_APIVERSION, apiVersion);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CrossVersionObjectReferenceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CrossVersionObjectReferenceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CrossVersionObjectReference<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CrossVersionObjectReference<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CrossVersionObjectReference");
      ds.field("kind", &self.kind());
      ds.field("name", &self.name());
      ds.field("apiVersion", &self.apiVersion());
      ds.finish()
  }
}
