// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum SelectableFieldOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SelectableField<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SelectableField<'a> {
  type Inner = SelectableField<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SelectableField<'a> {
  pub const VT_JSONPATH: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SelectableField { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SelectableFieldArgs<'args>
  ) -> flatbuffers::WIPOffset<SelectableField<'bldr>> {
    let mut builder = SelectableFieldBuilder::new(_fbb);
    if let Some(x) = args.jsonPath { builder.add_jsonPath(x); }
    builder.finish()
  }


  #[inline]
  pub fn jsonPath(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SelectableField::VT_JSONPATH, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for SelectableField<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("jsonPath", Self::VT_JSONPATH, false)?
     .finish();
    Ok(())
  }
}
pub struct SelectableFieldArgs<'a> {
    pub jsonPath: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for SelectableFieldArgs<'a> {
  #[inline]
  fn default() -> Self {
    SelectableFieldArgs {
      jsonPath: None,
    }
  }
}

impl Serialize for SelectableField<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("SelectableField", 1)?;
      s.serialize_field("jsonPath", &self.jsonPath())?;
    s.end()
  }
}

pub struct SelectableFieldBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SelectableFieldBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_jsonPath(&mut self, jsonPath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SelectableField::VT_JSONPATH, jsonPath);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SelectableFieldBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SelectableFieldBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SelectableField<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SelectableField<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SelectableField");
      ds.field("jsonPath", &self.jsonPath());
      ds.finish()
  }
}
