// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RBDPersistentVolumeSourceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RBDPersistentVolumeSource<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RBDPersistentVolumeSource<'a> {
  type Inner = RBDPersistentVolumeSource<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RBDPersistentVolumeSource<'a> {
  pub const VT_MONITORS: flatbuffers::VOffsetT = 4;
  pub const VT_IMAGE: flatbuffers::VOffsetT = 6;
  pub const VT_FSTYPE: flatbuffers::VOffsetT = 8;
  pub const VT_POOL: flatbuffers::VOffsetT = 10;
  pub const VT_USER: flatbuffers::VOffsetT = 12;
  pub const VT_KEYRING: flatbuffers::VOffsetT = 14;
  pub const VT_SECRETREF: flatbuffers::VOffsetT = 16;
  pub const VT_READONLY: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RBDPersistentVolumeSource { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RBDPersistentVolumeSourceArgs<'args>
  ) -> flatbuffers::WIPOffset<RBDPersistentVolumeSource<'bldr>> {
    let mut builder = RBDPersistentVolumeSourceBuilder::new(_fbb);
    if let Some(x) = args.secretRef { builder.add_secretRef(x); }
    if let Some(x) = args.keyring { builder.add_keyring(x); }
    if let Some(x) = args.user { builder.add_user(x); }
    if let Some(x) = args.pool { builder.add_pool(x); }
    if let Some(x) = args.fsType { builder.add_fsType(x); }
    if let Some(x) = args.image { builder.add_image(x); }
    if let Some(x) = args.monitors { builder.add_monitors(x); }
    builder.add_readOnly(args.readOnly);
    builder.finish()
  }


  #[inline]
  pub fn monitors(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(RBDPersistentVolumeSource::VT_MONITORS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn image(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RBDPersistentVolumeSource::VT_IMAGE, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn fsType(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RBDPersistentVolumeSource::VT_FSTYPE, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn pool(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RBDPersistentVolumeSource::VT_POOL, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn user(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RBDPersistentVolumeSource::VT_USER, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn keyring(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RBDPersistentVolumeSource::VT_KEYRING, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn secretRef(&self) -> SecretReference<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<SecretReference>>(RBDPersistentVolumeSource::VT_SECRETREF, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn readOnly(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(RBDPersistentVolumeSource::VT_READONLY, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RBDPersistentVolumeSource<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("monitors", Self::VT_MONITORS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("image", Self::VT_IMAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("fsType", Self::VT_FSTYPE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("pool", Self::VT_POOL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("user", Self::VT_USER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("keyring", Self::VT_KEYRING, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<SecretReference>>("secretRef", Self::VT_SECRETREF, false)?
     .visit_field::<bool>("readOnly", Self::VT_READONLY, false)?
     .finish();
    Ok(())
  }
}
pub struct RBDPersistentVolumeSourceArgs<'a> {
    pub monitors: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub image: Option<flatbuffers::WIPOffset<&'a str>>,
    pub fsType: Option<flatbuffers::WIPOffset<&'a str>>,
    pub pool: Option<flatbuffers::WIPOffset<&'a str>>,
    pub user: Option<flatbuffers::WIPOffset<&'a str>>,
    pub keyring: Option<flatbuffers::WIPOffset<&'a str>>,
    pub secretRef: Option<flatbuffers::WIPOffset<SecretReference<'a>>>,
    pub readOnly: bool,
}
impl<'a> Default for RBDPersistentVolumeSourceArgs<'a> {
  #[inline]
  fn default() -> Self {
    RBDPersistentVolumeSourceArgs {
      monitors: None,
      image: None,
      fsType: None,
      pool: None,
      user: None,
      keyring: None,
      secretRef: None,
      readOnly: false,
    }
  }
}

impl Serialize for RBDPersistentVolumeSource<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("RBDPersistentVolumeSource", 8)?;
      s.serialize_field("monitors", &self.monitors())?;
      s.serialize_field("image", &self.image())?;
      s.serialize_field("fsType", &self.fsType())?;
      s.serialize_field("pool", &self.pool())?;
      s.serialize_field("user", &self.user())?;
      s.serialize_field("keyring", &self.keyring())?;
      s.serialize_field("secretRef", &self.secretRef())?;
      s.serialize_field("readOnly", &self.readOnly())?;
    s.end()
  }
}

pub struct RBDPersistentVolumeSourceBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RBDPersistentVolumeSourceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_monitors(&mut self, monitors: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RBDPersistentVolumeSource::VT_MONITORS, monitors);
  }
  #[inline]
  pub fn add_image(&mut self, image: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RBDPersistentVolumeSource::VT_IMAGE, image);
  }
  #[inline]
  pub fn add_fsType(&mut self, fsType: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RBDPersistentVolumeSource::VT_FSTYPE, fsType);
  }
  #[inline]
  pub fn add_pool(&mut self, pool: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RBDPersistentVolumeSource::VT_POOL, pool);
  }
  #[inline]
  pub fn add_user(&mut self, user: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RBDPersistentVolumeSource::VT_USER, user);
  }
  #[inline]
  pub fn add_keyring(&mut self, keyring: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RBDPersistentVolumeSource::VT_KEYRING, keyring);
  }
  #[inline]
  pub fn add_secretRef(&mut self, secretRef: flatbuffers::WIPOffset<SecretReference<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<SecretReference>>(RBDPersistentVolumeSource::VT_SECRETREF, secretRef);
  }
  #[inline]
  pub fn add_readOnly(&mut self, readOnly: bool) {
    self.fbb_.push_slot::<bool>(RBDPersistentVolumeSource::VT_READONLY, readOnly, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RBDPersistentVolumeSourceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RBDPersistentVolumeSourceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RBDPersistentVolumeSource<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RBDPersistentVolumeSource<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RBDPersistentVolumeSource");
      ds.field("monitors", &self.monitors());
      ds.field("image", &self.image());
      ds.field("fsType", &self.fsType());
      ds.field("pool", &self.pool());
      ds.field("user", &self.user());
      ds.field("keyring", &self.keyring());
      ds.field("secretRef", &self.secretRef());
      ds.field("readOnly", &self.readOnly());
      ds.finish()
  }
}
