[package]
name = "cluster-types"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
prost = {version = "0.13.2"}
prost-types = {version = "0.13.2"}


[build-dependencies]
prost-build = {version = "0.13.2"}