// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ClusterTrustBundleProjectionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ClusterTrustBundleProjection<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ClusterTrustBundleProjection<'a> {
  type Inner = ClusterTrustBundleProjection<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ClusterTrustBundleProjection<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_SIGNERNAME: flatbuffers::VOffsetT = 6;
  pub const VT_LABELSELECTOR: flatbuffers::VOffsetT = 8;
  pub const VT_OPTIONAL: flatbuffers::VOffsetT = 10;
  pub const VT_PATH: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ClusterTrustBundleProjection { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ClusterTrustBundleProjectionArgs<'args>
  ) -> flatbuffers::WIPOffset<ClusterTrustBundleProjection<'bldr>> {
    let mut builder = ClusterTrustBundleProjectionBuilder::new(_fbb);
    if let Some(x) = args.path { builder.add_path(x); }
    if let Some(x) = args.labelSelector { builder.add_labelSelector(x); }
    if let Some(x) = args.signerName { builder.add_signerName(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_optional(args.optional);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ClusterTrustBundleProjection::VT_NAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn signerName(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ClusterTrustBundleProjection::VT_SIGNERNAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn labelSelector(&self) -> super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(ClusterTrustBundleProjection::VT_LABELSELECTOR, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn optional(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ClusterTrustBundleProjection::VT_OPTIONAL, Some(false)).unwrap()}
  }
  #[inline]
  pub fn path(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ClusterTrustBundleProjection::VT_PATH, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for ClusterTrustBundleProjection<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("signerName", Self::VT_SIGNERNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>("labelSelector", Self::VT_LABELSELECTOR, false)?
     .visit_field::<bool>("optional", Self::VT_OPTIONAL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("path", Self::VT_PATH, false)?
     .finish();
    Ok(())
  }
}
pub struct ClusterTrustBundleProjectionArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub signerName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub labelSelector: Option<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'a>>>,
    pub optional: bool,
    pub path: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ClusterTrustBundleProjectionArgs<'a> {
  #[inline]
  fn default() -> Self {
    ClusterTrustBundleProjectionArgs {
      name: None,
      signerName: None,
      labelSelector: None,
      optional: false,
      path: None,
    }
  }
}

impl Serialize for ClusterTrustBundleProjection<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("ClusterTrustBundleProjection", 5)?;
      s.serialize_field("name", &self.name())?;
      s.serialize_field("signerName", &self.signerName())?;
      s.serialize_field("labelSelector", &self.labelSelector())?;
      s.serialize_field("optional", &self.optional())?;
      s.serialize_field("path", &self.path())?;
    s.end()
  }
}

pub struct ClusterTrustBundleProjectionBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ClusterTrustBundleProjectionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ClusterTrustBundleProjection::VT_NAME, name);
  }
  #[inline]
  pub fn add_signerName(&mut self, signerName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ClusterTrustBundleProjection::VT_SIGNERNAME, signerName);
  }
  #[inline]
  pub fn add_labelSelector(&mut self, labelSelector: flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::super::super::apimachinery::pkg::apis::meta::v_1::LabelSelector>>(ClusterTrustBundleProjection::VT_LABELSELECTOR, labelSelector);
  }
  #[inline]
  pub fn add_optional(&mut self, optional: bool) {
    self.fbb_.push_slot::<bool>(ClusterTrustBundleProjection::VT_OPTIONAL, optional, false);
  }
  #[inline]
  pub fn add_path(&mut self, path: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ClusterTrustBundleProjection::VT_PATH, path);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ClusterTrustBundleProjectionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ClusterTrustBundleProjectionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ClusterTrustBundleProjection<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ClusterTrustBundleProjection<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ClusterTrustBundleProjection");
      ds.field("name", &self.name());
      ds.field("signerName", &self.signerName());
      ds.field("labelSelector", &self.labelSelector());
      ds.field("optional", &self.optional());
      ds.field("path", &self.path());
      ds.finish()
  }
}
