// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ClientIPConfigOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ClientIPConfig<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ClientIPConfig<'a> {
  type Inner = ClientIPConfig<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ClientIPConfig<'a> {
  pub const VT_TIMEOUTSECONDS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ClientIPConfig { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ClientIPConfigArgs
  ) -> flatbuffers::WIPOffset<ClientIPConfig<'bldr>> {
    let mut builder = ClientIPConfigBuilder::new(_fbb);
    builder.add_timeoutSeconds(args.timeoutSeconds);
    builder.finish()
  }


  #[inline]
  pub fn timeoutSeconds(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ClientIPConfig::VT_TIMEOUTSECONDS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ClientIPConfig<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("timeoutSeconds", Self::VT_TIMEOUTSECONDS, false)?
     .finish();
    Ok(())
  }
}
pub struct ClientIPConfigArgs {
    pub timeoutSeconds: i32,
}
impl<'a> Default for ClientIPConfigArgs {
  #[inline]
  fn default() -> Self {
    ClientIPConfigArgs {
      timeoutSeconds: 0,
    }
  }
}

impl Serialize for ClientIPConfig<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("ClientIPConfig", 1)?;
      s.serialize_field("timeoutSeconds", &self.timeoutSeconds())?;
    s.end()
  }
}

pub struct ClientIPConfigBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ClientIPConfigBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_timeoutSeconds(&mut self, timeoutSeconds: i32) {
    self.fbb_.push_slot::<i32>(ClientIPConfig::VT_TIMEOUTSECONDS, timeoutSeconds, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ClientIPConfigBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ClientIPConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ClientIPConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ClientIPConfig<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ClientIPConfig");
      ds.field("timeoutSeconds", &self.timeoutSeconds());
      ds.finish()
  }
}
