// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum APIGroupOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct APIGroup<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for APIGroup<'a> {
  type Inner = APIGroup<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> APIGroup<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_VERSIONS: flatbuffers::VOffsetT = 6;
  pub const VT_PREFERREDVERSION: flatbuffers::VOffsetT = 8;
  pub const VT_SERVERADDRESSBYCLIENTCIDRS: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    APIGroup { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args APIGroupArgs<'args>
  ) -> flatbuffers::WIPOffset<APIGroup<'bldr>> {
    let mut builder = APIGroupBuilder::new(_fbb);
    if let Some(x) = args.serverAddressByClientCIDRs { builder.add_serverAddressByClientCIDRs(x); }
    if let Some(x) = args.preferredVersion { builder.add_preferredVersion(x); }
    if let Some(x) = args.versions { builder.add_versions(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(APIGroup::VT_NAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn versions(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GroupVersionForDiscovery<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GroupVersionForDiscovery>>>>(APIGroup::VT_VERSIONS, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn preferredVersion(&self) -> GroupVersionForDiscovery<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<GroupVersionForDiscovery>>(APIGroup::VT_PREFERREDVERSION, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn serverAddressByClientCIDRs(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ServerAddressByClientCIDR<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ServerAddressByClientCIDR>>>>(APIGroup::VT_SERVERADDRESSBYCLIENTCIDRS, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for APIGroup<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<GroupVersionForDiscovery>>>>("versions", Self::VT_VERSIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<GroupVersionForDiscovery>>("preferredVersion", Self::VT_PREFERREDVERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ServerAddressByClientCIDR>>>>("serverAddressByClientCIDRs", Self::VT_SERVERADDRESSBYCLIENTCIDRS, false)?
     .finish();
    Ok(())
  }
}
pub struct APIGroupArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub versions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<GroupVersionForDiscovery<'a>>>>>,
    pub preferredVersion: Option<flatbuffers::WIPOffset<GroupVersionForDiscovery<'a>>>,
    pub serverAddressByClientCIDRs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ServerAddressByClientCIDR<'a>>>>>,
}
impl<'a> Default for APIGroupArgs<'a> {
  #[inline]
  fn default() -> Self {
    APIGroupArgs {
      name: None,
      versions: None,
      preferredVersion: None,
      serverAddressByClientCIDRs: None,
    }
  }
}

impl Serialize for APIGroup<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("APIGroup", 4)?;
      s.serialize_field("name", &self.name())?;
      s.serialize_field("versions", &self.versions())?;
      s.serialize_field("preferredVersion", &self.preferredVersion())?;
      s.serialize_field("serverAddressByClientCIDRs", &self.serverAddressByClientCIDRs())?;
    s.end()
  }
}

pub struct APIGroupBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> APIGroupBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(APIGroup::VT_NAME, name);
  }
  #[inline]
  pub fn add_versions(&mut self, versions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<GroupVersionForDiscovery<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(APIGroup::VT_VERSIONS, versions);
  }
  #[inline]
  pub fn add_preferredVersion(&mut self, preferredVersion: flatbuffers::WIPOffset<GroupVersionForDiscovery<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<GroupVersionForDiscovery>>(APIGroup::VT_PREFERREDVERSION, preferredVersion);
  }
  #[inline]
  pub fn add_serverAddressByClientCIDRs(&mut self, serverAddressByClientCIDRs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ServerAddressByClientCIDR<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(APIGroup::VT_SERVERADDRESSBYCLIENTCIDRS, serverAddressByClientCIDRs);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> APIGroupBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    APIGroupBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<APIGroup<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for APIGroup<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("APIGroup");
      ds.field("name", &self.name());
      ds.field("versions", &self.versions());
      ds.field("preferredVersion", &self.preferredVersion());
      ds.field("serverAddressByClientCIDRs", &self.serverAddressByClientCIDRs());
      ds.finish()
  }
}
