// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum VolumeNodeResourcesOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct VolumeNodeResources<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VolumeNodeResources<'a> {
  type Inner = VolumeNodeResources<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> VolumeNodeResources<'a> {
  pub const VT_COUNT: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    VolumeNodeResources { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VolumeNodeResourcesArgs
  ) -> flatbuffers::WIPOffset<VolumeNodeResources<'bldr>> {
    let mut builder = VolumeNodeResourcesBuilder::new(_fbb);
    builder.add_count(args.count);
    builder.finish()
  }


  #[inline]
  pub fn count(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(VolumeNodeResources::VT_COUNT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for VolumeNodeResources<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("count", Self::VT_COUNT, false)?
     .finish();
    Ok(())
  }
}
pub struct VolumeNodeResourcesArgs {
    pub count: i32,
}
impl<'a> Default for VolumeNodeResourcesArgs {
  #[inline]
  fn default() -> Self {
    VolumeNodeResourcesArgs {
      count: 0,
    }
  }
}

impl Serialize for VolumeNodeResources<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("VolumeNodeResources", 1)?;
      s.serialize_field("count", &self.count())?;
    s.end()
  }
}

pub struct VolumeNodeResourcesBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> VolumeNodeResourcesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_count(&mut self, count: i32) {
    self.fbb_.push_slot::<i32>(VolumeNodeResources::VT_COUNT, count, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> VolumeNodeResourcesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VolumeNodeResourcesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VolumeNodeResources<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for VolumeNodeResources<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("VolumeNodeResources");
      ds.field("count", &self.count());
      ds.finish()
  }
}
