// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ScaleSpecOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ScaleSpec<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ScaleSpec<'a> {
  type Inner = ScaleSpec<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ScaleSpec<'a> {
  pub const VT_REPLICAS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ScaleSpec { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ScaleSpecArgs
  ) -> flatbuffers::WIPOffset<ScaleSpec<'bldr>> {
    let mut builder = ScaleSpecBuilder::new(_fbb);
    builder.add_replicas(args.replicas);
    builder.finish()
  }


  #[inline]
  pub fn replicas(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ScaleSpec::VT_REPLICAS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ScaleSpec<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("replicas", Self::VT_REPLICAS, false)?
     .finish();
    Ok(())
  }
}
pub struct ScaleSpecArgs {
    pub replicas: i32,
}
impl<'a> Default for ScaleSpecArgs {
  #[inline]
  fn default() -> Self {
    ScaleSpecArgs {
      replicas: 0,
    }
  }
}

impl Serialize for ScaleSpec<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("ScaleSpec", 1)?;
      s.serialize_field("replicas", &self.replicas())?;
    s.end()
  }
}

pub struct ScaleSpecBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ScaleSpecBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_replicas(&mut self, replicas: i32) {
    self.fbb_.push_slot::<i32>(ScaleSpec::VT_REPLICAS, replicas, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ScaleSpecBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ScaleSpecBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ScaleSpec<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ScaleSpec<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ScaleSpec");
      ds.field("replicas", &self.replicas());
      ds.finish()
  }
}
