// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum StatefulSetOrdinalsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StatefulSetOrdinals<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for StatefulSetOrdinals<'a> {
  type Inner = StatefulSetOrdinals<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> StatefulSetOrdinals<'a> {
  pub const VT_START: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    StatefulSetOrdinals { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StatefulSetOrdinalsArgs
  ) -> flatbuffers::WIPOffset<StatefulSetOrdinals<'bldr>> {
    let mut builder = StatefulSetOrdinalsBuilder::new(_fbb);
    builder.add_start(args.start);
    builder.finish()
  }


  #[inline]
  pub fn start(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(StatefulSetOrdinals::VT_START, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for StatefulSetOrdinals<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("start", Self::VT_START, false)?
     .finish();
    Ok(())
  }
}
pub struct StatefulSetOrdinalsArgs {
    pub start: i32,
}
impl<'a> Default for StatefulSetOrdinalsArgs {
  #[inline]
  fn default() -> Self {
    StatefulSetOrdinalsArgs {
      start: 0,
    }
  }
}

impl Serialize for StatefulSetOrdinals<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("StatefulSetOrdinals", 1)?;
      s.serialize_field("start", &self.start())?;
    s.end()
  }
}

pub struct StatefulSetOrdinalsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StatefulSetOrdinalsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_start(&mut self, start: i32) {
    self.fbb_.push_slot::<i32>(StatefulSetOrdinals::VT_START, start, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> StatefulSetOrdinalsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StatefulSetOrdinalsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<StatefulSetOrdinals<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for StatefulSetOrdinals<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("StatefulSetOrdinals");
      ds.field("start", &self.start());
      ds.finish()
  }
}
