// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TolerationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Toleration<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Toleration<'a> {
  type Inner = Toleration<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Toleration<'a> {
  pub const VT_KEY: flatbuffers::VOffsetT = 4;
  pub const VT_OPERATOR: flatbuffers::VOffsetT = 6;
  pub const VT_VALUE: flatbuffers::VOffsetT = 8;
  pub const VT_EFFECT: flatbuffers::VOffsetT = 10;
  pub const VT_TOLERATIONSECONDS: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Toleration { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TolerationArgs<'args>
  ) -> flatbuffers::WIPOffset<Toleration<'bldr>> {
    let mut builder = TolerationBuilder::new(_fbb);
    builder.add_tolerationSeconds(args.tolerationSeconds);
    if let Some(x) = args.effect { builder.add_effect(x); }
    if let Some(x) = args.value { builder.add_value(x); }
    if let Some(x) = args.operator { builder.add_operator(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Toleration::VT_KEY, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn operator(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Toleration::VT_OPERATOR, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn value(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Toleration::VT_VALUE, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn effect(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Toleration::VT_EFFECT, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn tolerationSeconds(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Toleration::VT_TOLERATIONSECONDS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Toleration<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("operator", Self::VT_OPERATOR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("value", Self::VT_VALUE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("effect", Self::VT_EFFECT, false)?
     .visit_field::<i64>("tolerationSeconds", Self::VT_TOLERATIONSECONDS, false)?
     .finish();
    Ok(())
  }
}
pub struct TolerationArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    pub operator: Option<flatbuffers::WIPOffset<&'a str>>,
    pub value: Option<flatbuffers::WIPOffset<&'a str>>,
    pub effect: Option<flatbuffers::WIPOffset<&'a str>>,
    pub tolerationSeconds: i64,
}
impl<'a> Default for TolerationArgs<'a> {
  #[inline]
  fn default() -> Self {
    TolerationArgs {
      key: None,
      operator: None,
      value: None,
      effect: None,
      tolerationSeconds: 0,
    }
  }
}

impl Serialize for Toleration<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("Toleration", 5)?;
      s.serialize_field("key", &self.key())?;
      s.serialize_field("operator", &self.operator())?;
      s.serialize_field("value", &self.value())?;
      s.serialize_field("effect", &self.effect())?;
      s.serialize_field("tolerationSeconds", &self.tolerationSeconds())?;
    s.end()
  }
}

pub struct TolerationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TolerationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toleration::VT_KEY, key);
  }
  #[inline]
  pub fn add_operator(&mut self, operator: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toleration::VT_OPERATOR, operator);
  }
  #[inline]
  pub fn add_value(&mut self, value: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toleration::VT_VALUE, value);
  }
  #[inline]
  pub fn add_effect(&mut self, effect: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Toleration::VT_EFFECT, effect);
  }
  #[inline]
  pub fn add_tolerationSeconds(&mut self, tolerationSeconds: i64) {
    self.fbb_.push_slot::<i64>(Toleration::VT_TOLERATIONSECONDS, tolerationSeconds, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TolerationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TolerationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Toleration<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Toleration<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Toleration");
      ds.field("key", &self.key());
      ds.field("operator", &self.operator());
      ds.field("value", &self.value());
      ds.field("effect", &self.effect());
      ds.field("tolerationSeconds", &self.tolerationSeconds());
      ds.finish()
  }
}
