[package]
name = "exampler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.132" }
serde = { version = "1.0.213" }
protobuf = "3.7.1"
k8s-protos = {path = "../k8s-protos"}