// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum VolumeNodeAffinityOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct VolumeNodeAffinity<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VolumeNodeAffinity<'a> {
  type Inner = VolumeNodeAffinity<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> VolumeNodeAffinity<'a> {
  pub const VT_REQUIRED: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    VolumeNodeAffinity { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VolumeNodeAffinityArgs<'args>
  ) -> flatbuffers::WIPOffset<VolumeNodeAffinity<'bldr>> {
    let mut builder = VolumeNodeAffinityBuilder::new(_fbb);
    if let Some(x) = args.required { builder.add_required(x); }
    builder.finish()
  }


  #[inline]
  pub fn required(&self) -> NodeSelector<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<NodeSelector>>(VolumeNodeAffinity::VT_REQUIRED, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for VolumeNodeAffinity<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<NodeSelector>>("required", Self::VT_REQUIRED, false)?
     .finish();
    Ok(())
  }
}
pub struct VolumeNodeAffinityArgs<'a> {
    pub required: Option<flatbuffers::WIPOffset<NodeSelector<'a>>>,
}
impl<'a> Default for VolumeNodeAffinityArgs<'a> {
  #[inline]
  fn default() -> Self {
    VolumeNodeAffinityArgs {
      required: None,
    }
  }
}

impl Serialize for VolumeNodeAffinity<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("VolumeNodeAffinity", 1)?;
      s.serialize_field("required", &self.required())?;
    s.end()
  }
}

pub struct VolumeNodeAffinityBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> VolumeNodeAffinityBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_required(&mut self, required: flatbuffers::WIPOffset<NodeSelector<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<NodeSelector>>(VolumeNodeAffinity::VT_REQUIRED, required);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> VolumeNodeAffinityBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VolumeNodeAffinityBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VolumeNodeAffinity<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for VolumeNodeAffinity<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("VolumeNodeAffinity");
      ds.field("required", &self.required());
      ds.finish()
  }
}
