// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ReplicationControllerSpecOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReplicationControllerSpec<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ReplicationControllerSpec<'a> {
  type Inner = ReplicationControllerSpec<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ReplicationControllerSpec<'a> {
  pub const VT_REPLICAS: flatbuffers::VOffsetT = 4;
  pub const VT_MINREADYSECONDS: flatbuffers::VOffsetT = 6;
  pub const VT_SELECTOR: flatbuffers::VOffsetT = 8;
  pub const VT_TEMPLATE: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ReplicationControllerSpec { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReplicationControllerSpecArgs<'args>
  ) -> flatbuffers::WIPOffset<ReplicationControllerSpec<'bldr>> {
    let mut builder = ReplicationControllerSpecBuilder::new(_fbb);
    if let Some(x) = args.template { builder.add_template(x); }
    if let Some(x) = args.selector { builder.add_selector(x); }
    builder.add_minReadySeconds(args.minReadySeconds);
    builder.add_replicas(args.replicas);
    builder.finish()
  }


  #[inline]
  pub fn replicas(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ReplicationControllerSpec::VT_REPLICAS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn minReadySeconds(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ReplicationControllerSpec::VT_MINREADYSECONDS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn selector(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<replication_controller_spec_::SelectorEntry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<replication_controller_spec_::SelectorEntry>>>>(ReplicationControllerSpec::VT_SELECTOR, Some(Default::default())).unwrap()}
  }
  #[inline]
  pub fn template(&self) -> PodTemplateSpec<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<PodTemplateSpec>>(ReplicationControllerSpec::VT_TEMPLATE, Some(Default::default())).unwrap()}
  }
}

impl flatbuffers::Verifiable for ReplicationControllerSpec<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("replicas", Self::VT_REPLICAS, false)?
     .visit_field::<i32>("minReadySeconds", Self::VT_MINREADYSECONDS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<replication_controller_spec_::SelectorEntry>>>>("selector", Self::VT_SELECTOR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<PodTemplateSpec>>("template", Self::VT_TEMPLATE, false)?
     .finish();
    Ok(())
  }
}
pub struct ReplicationControllerSpecArgs<'a> {
    pub replicas: i32,
    pub minReadySeconds: i32,
    pub selector: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<replication_controller_spec_::SelectorEntry<'a>>>>>,
    pub template: Option<flatbuffers::WIPOffset<PodTemplateSpec<'a>>>,
}
impl<'a> Default for ReplicationControllerSpecArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReplicationControllerSpecArgs {
      replicas: 0,
      minReadySeconds: 0,
      selector: None,
      template: None,
    }
  }
}

impl Serialize for ReplicationControllerSpec<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("ReplicationControllerSpec", 4)?;
      s.serialize_field("replicas", &self.replicas())?;
      s.serialize_field("minReadySeconds", &self.minReadySeconds())?;
      s.serialize_field("selector", &self.selector())?;
      s.serialize_field("template", &self.template())?;
    s.end()
  }
}

pub struct ReplicationControllerSpecBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ReplicationControllerSpecBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_replicas(&mut self, replicas: i32) {
    self.fbb_.push_slot::<i32>(ReplicationControllerSpec::VT_REPLICAS, replicas, 0);
  }
  #[inline]
  pub fn add_minReadySeconds(&mut self, minReadySeconds: i32) {
    self.fbb_.push_slot::<i32>(ReplicationControllerSpec::VT_MINREADYSECONDS, minReadySeconds, 0);
  }
  #[inline]
  pub fn add_selector(&mut self, selector: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<replication_controller_spec_::SelectorEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ReplicationControllerSpec::VT_SELECTOR, selector);
  }
  #[inline]
  pub fn add_template(&mut self, template: flatbuffers::WIPOffset<PodTemplateSpec<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<PodTemplateSpec>>(ReplicationControllerSpec::VT_TEMPLATE, template);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ReplicationControllerSpecBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReplicationControllerSpecBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ReplicationControllerSpec<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ReplicationControllerSpec<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ReplicationControllerSpec");
      ds.field("replicas", &self.replicas());
      ds.field("minReadySeconds", &self.minReadySeconds());
      ds.field("selector", &self.selector());
      ds.field("template", &self.template());
      ds.finish()
  }
}
