// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum VolumeMountOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct VolumeMount<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VolumeMount<'a> {
  type Inner = VolumeMount<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> VolumeMount<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_READONLY: flatbuffers::VOffsetT = 6;
  pub const VT_RECURSIVEREADONLY: flatbuffers::VOffsetT = 8;
  pub const VT_MOUNTPATH: flatbuffers::VOffsetT = 10;
  pub const VT_SUBPATH: flatbuffers::VOffsetT = 12;
  pub const VT_MOUNTPROPAGATION: flatbuffers::VOffsetT = 14;
  pub const VT_SUBPATHEXPR: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    VolumeMount { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VolumeMountArgs<'args>
  ) -> flatbuffers::WIPOffset<VolumeMount<'bldr>> {
    let mut builder = VolumeMountBuilder::new(_fbb);
    if let Some(x) = args.subPathExpr { builder.add_subPathExpr(x); }
    if let Some(x) = args.mountPropagation { builder.add_mountPropagation(x); }
    if let Some(x) = args.subPath { builder.add_subPath(x); }
    if let Some(x) = args.mountPath { builder.add_mountPath(x); }
    if let Some(x) = args.recursiveReadOnly { builder.add_recursiveReadOnly(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_readOnly(args.readOnly);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(VolumeMount::VT_NAME, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn readOnly(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(VolumeMount::VT_READONLY, Some(false)).unwrap()}
  }
  #[inline]
  pub fn recursiveReadOnly(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(VolumeMount::VT_RECURSIVEREADONLY, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn mountPath(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(VolumeMount::VT_MOUNTPATH, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn subPath(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(VolumeMount::VT_SUBPATH, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn mountPropagation(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(VolumeMount::VT_MOUNTPROPAGATION, Some(&"0")).unwrap()}
  }
  #[inline]
  pub fn subPathExpr(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(VolumeMount::VT_SUBPATHEXPR, Some(&"0")).unwrap()}
  }
}

impl flatbuffers::Verifiable for VolumeMount<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<bool>("readOnly", Self::VT_READONLY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("recursiveReadOnly", Self::VT_RECURSIVEREADONLY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mountPath", Self::VT_MOUNTPATH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("subPath", Self::VT_SUBPATH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mountPropagation", Self::VT_MOUNTPROPAGATION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("subPathExpr", Self::VT_SUBPATHEXPR, false)?
     .finish();
    Ok(())
  }
}
pub struct VolumeMountArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub readOnly: bool,
    pub recursiveReadOnly: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mountPath: Option<flatbuffers::WIPOffset<&'a str>>,
    pub subPath: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mountPropagation: Option<flatbuffers::WIPOffset<&'a str>>,
    pub subPathExpr: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for VolumeMountArgs<'a> {
  #[inline]
  fn default() -> Self {
    VolumeMountArgs {
      name: None,
      readOnly: false,
      recursiveReadOnly: None,
      mountPath: None,
      subPath: None,
      mountPropagation: None,
      subPathExpr: None,
    }
  }
}

impl Serialize for VolumeMount<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("VolumeMount", 7)?;
      s.serialize_field("name", &self.name())?;
      s.serialize_field("readOnly", &self.readOnly())?;
      s.serialize_field("recursiveReadOnly", &self.recursiveReadOnly())?;
      s.serialize_field("mountPath", &self.mountPath())?;
      s.serialize_field("subPath", &self.subPath())?;
      s.serialize_field("mountPropagation", &self.mountPropagation())?;
      s.serialize_field("subPathExpr", &self.subPathExpr())?;
    s.end()
  }
}

pub struct VolumeMountBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> VolumeMountBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VolumeMount::VT_NAME, name);
  }
  #[inline]
  pub fn add_readOnly(&mut self, readOnly: bool) {
    self.fbb_.push_slot::<bool>(VolumeMount::VT_READONLY, readOnly, false);
  }
  #[inline]
  pub fn add_recursiveReadOnly(&mut self, recursiveReadOnly: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VolumeMount::VT_RECURSIVEREADONLY, recursiveReadOnly);
  }
  #[inline]
  pub fn add_mountPath(&mut self, mountPath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VolumeMount::VT_MOUNTPATH, mountPath);
  }
  #[inline]
  pub fn add_subPath(&mut self, subPath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VolumeMount::VT_SUBPATH, subPath);
  }
  #[inline]
  pub fn add_mountPropagation(&mut self, mountPropagation: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VolumeMount::VT_MOUNTPROPAGATION, mountPropagation);
  }
  #[inline]
  pub fn add_subPathExpr(&mut self, subPathExpr: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VolumeMount::VT_SUBPATHEXPR, subPathExpr);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> VolumeMountBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VolumeMountBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VolumeMount<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for VolumeMount<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("VolumeMount");
      ds.field("name", &self.name());
      ds.field("readOnly", &self.readOnly());
      ds.field("recursiveReadOnly", &self.recursiveReadOnly());
      ds.field("mountPath", &self.mountPath());
      ds.field("subPath", &self.subPath());
      ds.field("mountPropagation", &self.mountPropagation());
      ds.field("subPathExpr", &self.subPathExpr());
      ds.finish()
  }
}
