[package]
name = "k8s-protos"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "3.7.1"
serde = {version="1.0.213", features = ["derive"]}
serde_json = "1.0.132"
chrono = "0.4.38"
protobuf-json-mapping = "3.7.1"

[build-dependencies]
protobuf = "3.7.1"
protobuf-codegen = "3.7.1"